README.md

logion-network/logion-internal#159

chore: refer to new typescript backend.

---

src/common/CommonContext.tsx
src/common/Storage.test.tsx
src/common/Storage.tsx

logion-network/logion-internal#165

feat: tokens storage.

---

src/Login.tsx
src/common/Authentication.test.tsx
src/common/Authentication.tsx
src/common/CommonContext.tsx

logion-network/logion-internal#165

feat: use authentication API.

---

src/common/Authentication.test.tsx
src/common/Authentication.tsx
src/common/CommonContext.tsx
src/common/Storage.test.tsx
src/common/Storage.tsx
src/common/types/Addresses.test.ts
src/common/types/Addresses.ts

logion-network/logion-internal#165

feat: enable token refresh.

---

src/Login.test.tsx
src/Login.tsx
src/__mocks__/ReactRouterMock.ts
src/__snapshots__/Login.test.tsx.snap
src/common/AccountAddress.test.tsx
src/common/AccountAddress.tsx
src/common/AddressSwitcher.test.tsx
src/common/AddressSwitcher.tsx
src/common/Checkbox.tsx
src/common/Dashboard.tsx
src/common/__mocks__/Authentication.tsx
src/common/__mocks__/CommonContextMock.ts
src/common/__snapshots__/AddressSwitcher.test.tsx.snap
src/logion-chain/__mocks__/LogionChainMock.ts

logion-network/logion-internal#165

chore: add missing tests.

---

src/common/AddressSwitcher.tsx
src/common/__snapshots__/AddressSwitcher.test.tsx.snap

logion-network/logion-internal#177

feat: add logout confirmation.

---

package.json
src/__mocks__/PolkadotApiMock.ts
src/config/index.tsx
src/logion-chain/LogionLOC.test.tsx
src/logion-chain/LogionLOC.tsx
src/logion-chain/UUID.test.tsx
src/logion-chain/UUID.tsx
yarn.lock

logion-network/logion-internal#174

feat: add LOC creation to SDK.

---

src/legal-officer/LegalOfficerContext.test.tsx
src/legal-officer/LegalOfficerContext.tsx
src/legal-officer/Model.test.tsx
src/legal-officer/Model.tsx
src/legal-officer/PendingProtectionRequests.test.tsx
src/legal-officer/PendingProtectionRequests.tsx
src/legal-officer/RecoveryDetails.test.tsx
src/legal-officer/RecoveryDetails.tsx
src/legal-officer/TokenizationRequestAcceptance.test.tsx
src/legal-officer/TokenizationRequestAcceptance.tsx
src/wallet-user/Model.test.tsx
src/wallet-user/Model.tsx
src/wallet-user/Tokenization.test.tsx
src/wallet-user/Tokenization.tsx
src/wallet-user/UserContext.test.tsx
src/wallet-user/trust-protection/CreateProtectionRequestForm.test.tsx
src/wallet-user/trust-protection/CreateProtectionRequestForm.tsx
src/wallet-user/trust-protection/Model.test.tsx
src/wallet-user/trust-protection/Model.tsx

logion-network/logion-internal#179

feat: remove signature, signedOn from all endpoints except authenticate; remove useless sessionToken.

---

src/common/Model.ts
src/common/types/ModelTypes.ts
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/transaction-protection/LocCreationForm.tsx
src/wallet-user/transaction-protection/RequestedLocs.test.tsx
src/wallet-user/transaction-protection/RequestedLocs.tsx
src/wallet-user/transaction-protection/__snapshots__/RequestedLocs.test.tsx.snap

logion-network/logion-internal#180

feat: request identity info on LOC creation if not known.

---

src/common/LegalOfficerNameCell.tsx
src/common/UserIdentityNameCell.tsx
src/legal-officer/transaction-protection/LocRequests.tsx
src/legal-officer/transaction-protection/LocRequestsHistory.tsx
src/legal-officer/transaction-protection/OpenedLocs.tsx
src/legal-officer/transaction-protection/PendingLocRequests.tsx
src/legal-officer/transaction-protection/__snapshots__/LocRequestsHistory.test.tsx.snap
src/legal-officer/transaction-protection/__snapshots__/PendingLocRequests.test.tsx.snap
src/wallet-user/transaction-protection/OpenedLocs.tsx
src/wallet-user/transaction-protection/RejectedLocs.tsx
src/wallet-user/transaction-protection/RequestedLocs.tsx
src/wallet-user/transaction-protection/__snapshots__/RejectedLocs.test.tsx.snap
src/wallet-user/transaction-protection/__snapshots__/RequestedLocs.test.tsx.snap

logion-network/logion-internal#180

feat: align tables with specs.

---

src/__mocks__/PolkadotApiMock.ts
src/logion-chain/LogionLoc.test.tsx
src/logion-chain/LogionLoc.tsx
src/logion-chain/interfaces/augment-api-tx.ts
src/logion-chain/interfaces/default/types.ts
src/logion-chain/interfaces/definitions.ts

logion-network/logion-internal#189

feat: add hash with SDK.

---

src/__mocks__/PolkadotApiMock.ts
src/logion-chain/LogionLoc.tsx
src/logion-chain/Types.tsx

logion-network/logion-internal#189

fix: build failure with loc hashes

---

src/logion-chain/interfaces/augment-api-errors.ts
src/logion-chain/interfaces/augment-api-events.ts
src/logion-chain/interfaces/augment-api-tx.ts
src/logion-chain/interfaces/default/types.ts
src/logion-chain/interfaces/definitions.ts

logion-network/logion-internal#194

feat: upgrade custom types wrt closed LOC.

---

src/common/FileSelectorButton.tsx
src/legal-officer/Model.tsx
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/legal-officer/transaction-protection/LocContext.tsx
src/legal-officer/transaction-protection/LocItems.tsx
src/legal-officer/transaction-protection/LocPrivateFileButton.tsx
src/legal-officer/transaction-protection/LocPrivateFileDetails.tsx
src/legal-officer/transaction-protection/LocPrivateFileForm.tsx
src/legal-officer/transaction-protection/LocPublicDataDetails.tsx
src/legal-officer/transaction-protection/LocPublishPrivateFileButton.tsx
src/legal-officer/transaction-protection/LocPublishPublicDataButton.tsx

logion-network/logion-internal#191

feat: add file to loc.

---

src/common/Model.ts
src/legal-officer/transaction-protection/CloseLocButton.tsx
src/legal-officer/transaction-protection/LocContext.tsx
src/legal-officer/transaction-protection/LocPublishPrivateFileButton.tsx

logion-network/logion-internal#198

feat: confirm/delete files.

---

src/common/Model.ts
src/legal-officer/transaction-protection/LocContext.tsx

logion-network/logion-internal#195

feat: pre-close.

---

src/common/Model.ts
src/common/Table.tsx
src/common/types/ModelTypes.ts
src/legal-officer/transaction-protection/LocContext.tsx
src/legal-officer/transaction-protection/LocItems.tsx

logion-network/logion-internal#191

feat: sync timestamps and document name.

---

src/common/Model.ts
src/legal-officer/LegalOfficerPaths.tsx
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/legal-officer/transaction-protection/LocContext.tsx
src/legal-officer/transaction-protection/LocCreationDialog.tsx
src/legal-officer/transaction-protection/LocCreationForm.tsx
src/legal-officer/transaction-protection/LocCreationSteps.tsx
src/legal-officer/transaction-protection/LocDetails.tsx
src/legal-officer/transaction-protection/LocLinkButton.test.tsx
src/legal-officer/transaction-protection/LocLinkButton.tsx
src/legal-officer/transaction-protection/__snapshots__/LocLinkButton.test.tsx.snap

logion-network/logion-internal#211

feat: Link LOC to a new LOC.

---

src/__mocks__/PolkadotApiMock.ts
src/certificate/Certificate.tsx
src/common/types/ModelTypes.ts
src/legal-officer/PendingProtectionRequests.tsx
src/legal-officer/RecoveryDetails.tsx
src/legal-officer/transaction-protection/LocContext.tsx
src/legal-officer/transaction-protection/LocCreationDialog.tsx
src/legal-officer/transaction-protection/LocCreationForm.tsx
src/legal-officer/transaction-protection/LocItemFactory.ts
src/legal-officer/transaction-protection/LocLinkButton.tsx
src/legal-officer/transaction-protection/LocLinkExistingForm.tsx
src/legal-officer/transaction-protection/LocLinkExistingLocDialog.tsx
src/legal-officer/transaction-protection/LocPrivateFileButton.tsx
src/legal-officer/transaction-protection/LocPrivateFileDetails.tsx
src/legal-officer/transaction-protection/LocPrivateFileForm.tsx
src/legal-officer/transaction-protection/LocPublicDataDetails.tsx
src/legal-officer/transaction-protection/__snapshots__/LocLinkButton.test.tsx.snap
src/legal-officer/transaction-protection/__snapshots__/LocLinkExistingForm.test.tsx.snap
src/legal-officer/transaction-protection/types.ts
src/logion-chain/LogionLoc.test.tsx
src/logion-chain/LogionLoc.tsx
src/logion-chain/Types.tsx
src/logion-chain/interfaces/augment-api-errors.ts
src/logion-chain/interfaces/augment-api-tx.ts
src/logion-chain/interfaces/augment-types.ts
src/logion-chain/interfaces/default/types.ts
src/logion-chain/interfaces/definitions.ts
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/trust-protection/__snapshots__/CreateProtectionRequestForm.test.tsx.snap
yarn.lock

logion-network/logion-internal#227

feat: add links and nature.

---

src/common/Detail.tsx
src/legal-officer/ProtectedUserDetails.tsx
src/legal-officer/ProtectedUsers.tsx
src/legal-officer/ProtectionRequestsHistory.tsx
src/legal-officer/__snapshots__/ProtectedUsers.test.tsx.snap
src/legal-officer/__snapshots__/ProtectionRequestsHistory.test.tsx.snap
src/legal-officer/transaction-protection/LocCreationForm.tsx
src/legal-officer/transaction-protection/LocLinkExistingForm.tsx
src/legal-officer/transaction-protection/LocPrivateFileDetails.tsx
src/legal-officer/transaction-protection/LocPrivateFileForm.tsx
src/legal-officer/transaction-protection/LocPublicDataDetails.tsx
src/legal-officer/transaction-protection/__snapshots__/LocLinkExistingForm.test.tsx.snap

logion-network/logion-internal#220

feat: improve protected users table and add LOC ID column.

---

src/legal-officer/ProtectedUserDetails.tsx
src/legal-officer/ProtectedUsers.tsx
src/legal-officer/ProtectionRequestsHistory.tsx
src/legal-officer/__snapshots__/ProtectedUsers.test.tsx.snap
src/legal-officer/__snapshots__/ProtectionRequestsHistory.test.tsx.snap

logion-network/logion-internal#220

feat: replace LOC ID column with "Identity LOC" button.

---

src/common/Model.tsx

logion-network/logion-internal#222

feat: add transaction types for pallets logionLoc and verifiedRecovery.

---

src/legal-officer/transaction-protection/LocLinkButton.tsx

logion-network/logion-internal#248

fix: set nature of link to new LOC.

---

src/common/MainMenu.test.tsx
src/common/TestData.ts
src/common/TransactionStatusCell.css
src/common/TransactionStatusCell.test.tsx
src/common/TransactionStatusCell.tsx
src/common/Transactions.test.tsx
src/common/Transactions.tsx
src/common/__snapshots__/TransactionStatusCell.test.tsx.snap
src/common/__snapshots__/Transactions.test.tsx.snap
src/common/types/ModelTypes.ts
src/legal-officer/Home.tsx
src/legal-officer/__snapshots__/Home.test.tsx.snap
src/wallet-user/Home.tsx
src/wallet-user/__snapshots__/Home.test.tsx.snap

logion-network/logion-internal#252

feat: add status and error info to transactions.

---

src/common/hash.ts
src/legal-officer/transaction-protection/CheckFileFrame.tsx
src/legal-officer/transaction-protection/LocPrivateFileButton.tsx

logion-network/logion-internal#251

fix: prevent add duplicate hash to LOC.

---

src/legal-officer/Home.tsx
src/legal-officer/transaction-protection/LocRequestAcceptance.test.tsx
src/legal-officer/transaction-protection/LocRequestAcceptance.tsx

logion-network/logion-internal#255
logion-network/logion-internal#232

fix: accept after LOC opened + LO home fix.

---

src/certificate/Certificate.css
src/certificate/Certificate.tsx
src/common/FormGroup.css
src/legal-officer/transaction-protection/LocItemDetail.css
src/legal-officer/transaction-protection/LocPublicDataDetails.tsx
src/legal-officer/transaction-protection/LocPublicDataForm.tsx

logion-network/logion-internal#269

feat: support multiline metadata values.

---

src/certificate/Certificate.css
src/certificate/Certificate.tsx
src/common/InlineDateTime.tsx
src/common/NewTabLink.css
src/common/Tabs.css
src/common/Tabs.tsx
src/legal-officer/transaction-protection/ContextualizedLocDetails.css
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/legal-officer/transaction-protection/VoidLocReplaceExistingButton.tsx

logion-network/logion-internal#272

feat: adjustments.

---

src/legal-officer/transaction-protection/LocContext.tsx

logion-network/logion-internal#282

fix: loc link timestamp not shown.

---

src/common/CommonContext.tsx
src/common/types/Accounts.tsx
src/legal-officer/LegalOfficerContext.tsx
src/wallet-user/UserContext.tsx

logion-network/logion-internal#285

fix: 401s on refresh or switch.

---

README.md
package.json
public/version.json
scripts/pre-release.sh
src/App.tsx
src/Login.test.tsx
src/Login.tsx
src/__snapshots__/App.test.tsx.snap
src/__snapshots__/Login.test.tsx.snap
src/version/VersionContext.tsx
src/version/VersionContextMock.tsx
src/version/__mocks__/VersionContext.tsx
src/version/version.ts
yarn.lock

logion-network/logion-internal#283

feat: add version check.

---

src/common/types/ModelTypes.ts
src/legal-officer/Model.tsx
src/legal-officer/transaction-protection/LocContext.tsx
src/legal-officer/transaction-protection/LocItemFactory.ts
src/legal-officer/transaction-protection/LocPrivateFileButton.tsx
src/legal-officer/transaction-protection/LocPrivateFileForm.tsx

logion-network/logion-internal#280

feat: persist draft document to backend.

---

src/Login.test.tsx
src/Login.tsx
src/Settings.tsx
src/SettingsPane.css
src/SettingsPane.tsx
src/__snapshots__/Login.test.tsx.snap
src/common/Alert.tsx

logion-network/logion-internal#283

feat: move version information to settings.

---

src/legal-officer/transaction-protection/LocContext.tsx

logion-network/logion-internal#289

fix: app crashes on date refresh.

---

src/legal-officer/transaction-protection/CloseLocButton.tsx

logion-network/logion-internal#280

feat: disable Close LOC button when draft items are present.

---

src/common/CopyPasteButton.css
src/common/CopyPasteButton.tsx
src/common/LocIdCell.tsx
src/common/Table.tsx
src/common/__snapshots__/LocIdCell.test.tsx.snap
src/legal-officer/PendingProtectionRequests.tsx
src/legal-officer/ProtectedUserDetails.tsx
src/legal-officer/ProtectedUsers.tsx
src/legal-officer/ProtectionRequestsHistory.tsx
src/legal-officer/RecoveryRequestsHistory.tsx
src/legal-officer/__snapshots__/ProtectedUsers.test.tsx.snap
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/legal-officer/transaction-protection/LocItemDetail.tsx
src/legal-officer/transaction-protection/LocLinkDetails.tsx
src/legal-officer/transaction-protection/LocPrivateFileDetails.tsx
src/legal-officer/transaction-protection/LocPublicDataDetails.tsx
src/wallet-user/trust-protection/Officer.css
src/wallet-user/trust-protection/Officer.tsx
src/wallet-user/trust-protection/ProtectionRecoveryRequest.css
src/wallet-user/trust-protection/SelectLegalOfficer.css

logion-network/logion-internal#293

feat: add copy to clipboard button to all LOC ID and polkadot addresses.

---

src/legal-officer/transaction-protection/LocContext.tsx

logion-network/logion-internal#299

fix: reset LocContext on id update.

---

src/certificate/Certificate.tsx

logion-network/logion-internal#300

feat: adapt certificate to Logion Identity LOC.

---

src/common/Ellipsis.css
src/common/Ellipsis.tsx
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx

logion-network/logion-internal#299

feat: add link to logion identity LOC.

---

src/common/Wallet.css
src/common/Wallet.tsx
src/common/__snapshots__/Wallet.test.tsx.snap

logion-network/logion-internal#306

chore: move lgnt logo to gauge title.

---

src/legal-officer/Home.tsx
src/legal-officer/__snapshots__/Home.test.tsx.snap
src/legal-officer/transaction-protection/ContextualizedLocDetails.css
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/legal-officer/transaction-protection/IdentityProtection.tsx
src/legal-officer/transaction-protection/LocLinkButton.test.tsx
src/legal-officer/transaction-protection/LocLinkButton.tsx
src/legal-officer/transaction-protection/__snapshots__/LocLinkButton.test.tsx.snap

logion-network/logion-internal#299

chore: implement feedback from testing.

---

src/SettingsPane.tsx
src/common/Dashboard.css
src/common/Dashboard.test.tsx
src/common/Dashboard.tsx
src/common/__snapshots__/Dashboard.test.tsx.snap
src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/Home.tsx
src/legal-officer/LegalOfficerPaths.tsx
src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/PendingProtectionRequests.tsx
src/legal-officer/ProtectedUsers.tsx
src/legal-officer/ProtectionRequestsHistory.tsx
src/legal-officer/RecoveryDetails.tsx
src/legal-officer/__snapshots__/ContextualizedWallet.test.tsx.snap
src/legal-officer/__snapshots__/LegalOfficerRouter.test.tsx.snap
src/legal-officer/transaction-protection/ClosedLocs.tsx
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/legal-officer/transaction-protection/IdentityProtection.tsx
src/legal-officer/transaction-protection/LocItems.tsx
src/legal-officer/transaction-protection/LocLinkDetails.tsx
src/legal-officer/transaction-protection/OpenedLocs.tsx
src/legal-officer/transaction-protection/VoidLocs.tsx
src/wallet-user/ContextualizedWallet.tsx
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/ContextualizedWallet.test.tsx.snap
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap

logion-network/logion-internal#307

feat: fix navbar UI.

---

src/common/Dashboard.css
src/common/Frame.css
src/common/Wallet.tsx
src/common/__snapshots__/Wallet.test.tsx.snap
src/legal-officer/transaction-protection/ContextualizedLocDetails.tsx
src/wallet-user/trust-protection/GoToTrustProtection.css
src/wallet-user/trust-protection/GoToTrustProtection.tsx
src/wallet-user/trust-protection/RecoveryProcess.tsx

logion-network/logion-internal#296

feat: feedback.

---

src/legal-officer/transaction-protection/VoidLocReplaceExistingButton.tsx
src/legal-officer/transaction-protection/VoidLocReplaceNewButton.tsx

logion-network/logion-internal#299

chore: void loc: enforce replacer has same type.

---

src/loc/LocContext.tsx

logion-network/logion-internal#311

fix: wrong signer id given when publishing item.

---

src/common/SubmitterName.tsx
src/loc/LocItems.tsx

logion-network/logion-internal#314

fix: display submitter name.

---

src/loc/ContextualizedLocDetails.css

logion-network/logion-internal#311

feat: fix buttons alignment.

---

src/common/Storage.tsx
src/directory/DirectoryContext.tsx

logion-network/logion-internal#330

feat: handle directory failure.

---

src/directory/DirectoryContext.tsx

logion-network/logion-internal#325

feat: refresh on directory data save.

---

src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/__snapshots__/LegalOfficerRouter.test.tsx.snap

logion-network/logion-internal#325

feat: hide false-positive error connection message.

---

src/common/Model.tsx
src/common/__mocks__/Model.tsx
src/common/__mocks__/ModelMock.ts
src/loc/LocContext.test.tsx
src/loc/LocContext.tsx

logion-network/logion-internal#339

feat: show public link data only when no access.

---

src/common/TransactionConfirmation.test.tsx
src/common/TransactionConfirmation.tsx
src/common/WalletGauge.tsx
src/common/__snapshots__/WalletGauge.test.tsx.snap
src/wallet-user/trust-protection/RecoveryProcess.tsx

logion-network/logion-internal#326

feat: waiting message during recovery.

---

src/loc/LocItems.test.tsx
src/loc/LocItems.tsx
src/loc/__snapshots__/LocItems.test.tsx.snap

logion-network/logion-internal#339

feat: hide delete button if not allowed.

---

src/certificate/Certificate.tsx
src/common/LegalOfficerAdditionalDetails.css
src/common/LegalOfficerAdditionalDetails.tsx
src/settings/DirectoryData.tsx
src/wallet-user/trust-protection/Officer.tsx

logion-network/logion-internal#325

feat: fix update and display of additional details.

---

src/common/AddressSwitcher.css
src/common/AddressSwitcher.tsx

logion-network/logion-internal#343

feat: navigate to home page upon address switch; adapt width.

---

src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/transaction-protection/TransactionProtection.test.tsx
src/wallet-user/transaction-protection/TransactionProtection.tsx
src/wallet-user/transaction-protection/__snapshots__/TransactionProtection.test.tsx.snap

logion-network/logion-internal#350

chore: update request protection button label.

---

src/PublicRouter.tsx
src/certificate/Certificate.tsx
src/certificate/CollectionItemCellRow.tsx
src/certificate/IntroductionText.tsx
src/certificate/LegalOfficerRow.tsx
src/logion-chain/LogionLoc.tsx
src/logion-chain/Types.tsx

logion-network/logion-internal#349

feat: add collection item to certificate.

---

src/common/CommonContext.tsx
src/common/MenuItem.tsx
src/config/development.json
src/directory/DirectoryApi.ts
src/directory/DirectoryContext.tsx
src/legal-officer/ContextualizedWallet.test.tsx
src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/LegalOfficerRouter.test.tsx
src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/__snapshots__/ContextualizedWallet.test.tsx.snap
src/settings/DirectoryData.tsx

logion-network/logion-internal#364

feat: enable LO settings bootstrap.

---

package.json
src/certificate/Certificate.css
src/common/CheckedControl.tsx
src/common/DatePicker.css
src/common/DatePicker.tsx
src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLimitsForm.tsx
src/loc/ContextualizedLocDetails.tsx
yarn.lock

logion-network/logion-internal#346
logion-network/logion-internal#347

feat: handle feedback.

---

src/common/StaticLabelValue.css
src/common/StaticLabelValue.tsx
src/loc/CertificateAndLimits.css
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLocItemChecker.css
src/loc/CollectionLocItemChecker.tsx

logion-network/logion-internal#347

feat: handle feedback 2.

---

src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/logion-chain/Signature.test.tsx
src/logion-chain/Signature.tsx
src/logion-chain/__mocks__/SignatureMock.tsx

logion-network/logion-internal#371

fix: properly detect transaction errors.

---

src/common/CommonContext.tsx
src/common/__mocks__/CommonContextMock.ts

logion-network/logion-internal#381

fix: tentative fix of LOs seeing WU screen.

---

src/ExtrinsicSubmitter.test.tsx
src/ExtrinsicSubmitter.tsx
src/logion-chain/Signature.tsx
src/logion-chain/Vault.ts
src/logion-chain/__mocks__/SignatureMock.tsx
src/logion-chain/interfaces/augment-api-consts.ts
src/logion-chain/interfaces/augment-api-errors.ts
src/logion-chain/interfaces/augment-api-events.ts
src/logion-chain/interfaces/augment-api-query.ts
src/logion-chain/interfaces/augment-api-tx.ts

logion-network/logion-internal#394

feat: enable vault-out transfers.

---

src/common/Transactions.css
src/common/Transactions.tsx
src/common/VaultOutRequest.tsx
src/common/WalletGauge.tsx
src/wallet-user/trust-protection/Vault.css
src/wallet-user/trust-protection/Vault.tsx

logion-network/logion-internal#391

feat: fix vault style.

---

src/common/PendingVaultTransferRequests.tsx
src/common/Transactions.css
src/common/Transactions.tsx
src/logion-chain/Balances.ts
src/wallet-user/trust-protection/Vault.css

logion-network/logion-internal#391
logion-network/logion-internal#387

chore: user feedback.

---

public/assets/vault-big.svg
src/common/AddressFormat.css
src/common/AddressFormat.tsx
src/common/AmountCell.tsx
src/common/AmountFormat.tsx
src/common/Button.tsx
src/common/Clickable.tsx
src/common/CommonContext.tsx
src/common/DateTimeFormat.tsx
src/common/HandledVaultTransferRequests.tsx
src/common/MenuIcon.css
src/common/PendingVaultTransferRequests.tsx
src/common/StaticLabelValue.css
src/common/StaticLabelValue.tsx
src/common/VaultTransferRequestStatusCell.tsx
src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/LegalOfficerPaths.tsx
src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/__snapshots__/ContextualizedWallet.test.tsx.snap
src/legal-officer/__snapshots__/LegalOfficerRouter.test.tsx.snap
src/legal-officer/vault/PendingVaultTransferRequests.tsx
src/legal-officer/vault/VaultOutRequests.tsx
src/legal-officer/vault/VaultTransferDetails.tsx
src/legal-officer/vault/VaultTransferRequestsHistory.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/logion-chain/Vault.ts
src/vault/VaultApi.ts
src/vault/VaultOutRequest.tsx

logion-network/logion-internal#400

feat: vault transfer approval.

---

src/common/Model.tsx
src/common/PendingVaultTransferRequests.tsx
src/common/TestData.ts
src/common/Transactions.css
src/common/Transactions.tsx
src/common/TransferAmountCell.tsx
src/common/WalletGauge.tsx
src/common/types/ModelTypes.ts
src/legal-officer/__snapshots__/Home.test.tsx.snap
src/logion-chain/Vault.ts
src/vault/VaultOutRequest.tsx

logion-network/logion-internal#400

feat: register new tx types and improve transfer.

---

src/__mocks__/PolkadotApiMock.ts
src/common/Transactions.tsx
src/logion-chain/Balances.ts
src/logion-chain/Vault.ts

logion-network/logion-internal#410

feat: hide deposit in transactions.

---

src/common/CommonContext.tsx
src/common/RejectedVaultTransferRequests.tsx
src/common/RequestToCancel.tsx
src/common/VaultTransferRequestStatusCell.tsx
src/common/VaultTransferRequests.tsx
src/common/VaultTransferRequestsCallbacks.ts
src/legal-officer/vault/PendingVaultTransferRequests.tsx
src/legal-officer/vault/VaultTransferDetails.tsx
src/vault/VaultApi.ts

logion-network/logion-internal#388

feat: enable cancel/resubmit post reject.

---

package.json
src/logion-chain/numbers.test.ts
src/logion-chain/numbers.ts
yarn.lock

logion-network/logion-internal#409

feat: improve scientific to prefixed conversion.

---

src/logion-chain/Vault.ts
src/wallet-user/trust-protection/RecoveryProcess.test.tsx
src/wallet-user/trust-protection/RecoveryProcess.tsx
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
src/wallet-user/trust-protection/WalletRecoveryProcessTab.tsx

Vault Recovery

---

src/common/TestData.ts
src/common/__snapshots__/Wallet.test.tsx.snap
src/logion-chain/Balances.test.ts
src/logion-chain/Balances.ts
src/wallet-user/trust-protection/RecoveryProcess.test.tsx
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
src/wallet-user/trust-protection/WalletRecoveryProcessTab.tsx

fix: use available balance for recovery.

---

src/legal-officer/vault/PendingVaultTransferRequests.tsx
src/legal-officer/vault/VaultTransferDetails.tsx
src/vault/VaultApi.ts
src/vault/VaultOutRequest.tsx
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx

feat: set the origin for all vault transfers.

---

src/common/VaultTransferRequestsCallbacks.ts
src/logion-chain/Vault.ts

feat: enable cancel of vault recovery request.

---

src/common/CommonContext.tsx
src/common/HandledVaultTransferRequests.tsx
src/common/PendingVaultTransferRequests.tsx
src/common/RejectedVaultTransferRequests.tsx
src/common/RequestToCancel.tsx
src/common/TransactionConfirmation.css
src/common/TransactionConfirmation.test.tsx
src/common/TransactionConfirmation.tsx
src/legal-officer/vault/PendingVaultTransferRequests.tsx
src/legal-officer/vault/VaultTransferRequestsHistory.tsx
src/vault/VaultApi.ts
src/wallet-user/trust-protection/RecoveryProcess.css
src/wallet-user/trust-protection/VaultRecoveryProcessTab.css
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
src/wallet-user/trust-protection/WalletRecoveryProcessTab.tsx

feat: manage vault recovery request inside vault recovery.

---

src/certificate/Certificate.tsx
src/certificate/CollectionItemCellRow.tsx
src/loc/CollectionLocItemChecker.css
src/loc/CollectionLocItemChecker.tsx
src/loc/ContextualizedLocDetails.tsx

logion-network/logion-internal#416

feat: broaden document check scope.

---

src/loc/ContextualizedLocDetails.css
src/loc/LocCreationSteps.tsx
src/loc/VoidLocReplaceNewButton.tsx

logion-network/logion-internal#421

fix: void and replace collection LOC.

---

src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/LegalOfficerPaths.tsx
src/loc/CertificateAndLimits.css
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLocItemChecker.css
src/loc/CollectionLocItemChecker.tsx
src/loc/StatementOfFacts.tsx
src/loc/StatementOfFactsButton.css
src/loc/StatementOfFactsButton.tsx
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap
yarn.lock

logion-network/logion-internal#439

feat: scafold for statement of facts.

---

src/directory/DirectoryApi.ts
src/directory/DirectoryContextMock.tsx
src/loc/statement/PathModel.ts
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx
src/settings/DirectoryData.tsx
src/wallet-user/trust-protection/__snapshots__/CreateProtectionRequestForm.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/ProtectionRecoveryRequest.test.tsx.snap

logion-network/logion-internal#441

feat: custom logo in SOF.

---

src/common/Grid.css
src/loc/CollectionLocItemChecker.tsx
src/loc/statement/PathModel.ts
src/loc/statement/StatementOfFactsButton.tsx

logion-network/logion-internal#441

feat: fix SoF generation for item.

---

src/loc/CertificateAndLimits.tsx
src/loc/statement/PathModel.ts
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsForm.tsx
src/loc/statement/StatementOfFactsSummary.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

logion-network/logion-internal#440

feat: add LO Statement of Facts form.

---

src/loc/CollectionLocItemChecker.tsx
src/loc/ImportItems.tsx
src/loc/types.ts

logion-network/logion-internal#430

feat: handle feedback 3.

---

public/assets/preview.svg
src/common/Dialog.css
src/loc/statement/PathModel.ts
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsForm.css
src/loc/statement/StatementOfFactsForm.tsx
src/loc/statement/StatementOfFactsSummary.css
src/loc/statement/StatementOfFactsSummary.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

* remove download button, revamp summary, convert amounts to free text, styling.
* validate containing LOC.
logion-network/logion-internal#440

feedbak from test

---

src/loc/statement/StatementOfFactsTemplateEN.tsx

logion-network/logion-internal#441

feat: set english SoF template.

---

src/loc/statement/PathModel.ts
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsSummary.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

logion-network/logion-internal#431

feat: generates SOF for LOC having identity LOC as requester.

---

src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsSummary.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

logion-network/logion-internal#431

Feedback on SOF

---

public/statement.css
src/loc/LocContext.tsx
src/loc/LocPrivateFileButton.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

* feat: add spinner when uploading a file.
* minor format problem on SOF. 
logion-network/logion-internal#434
logion-network/logion-internal#431

feat: add spinner when uploading a file.

---

src/common/Model.tsx
src/loc/CertificateAndLimits.css
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLocItemChecker.test.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/LocContext.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/statement/StatementOfFactsRequestButton.test.tsx
src/loc/statement/StatementOfFactsRequestButton.tsx

logion-network/logion-internal#448

feat: add SOF request.

---

src/loc/LocContext.tsx

logion-network/logion-internal#451

fix: wrong backend targeted when user edits a LOC owned by LO while being connected to another LO's node.

---

src/loc/statement/StatementOfFactsRequestButton.test.tsx
src/loc/statement/StatementOfFactsRequestButton.tsx

logion-network/logion-internal#448
logion-network/logion-internal#449

feat: add dialog after sof is requested.

---

src/common/__mocks__/CommonContextMock.ts
src/legal-officer/Home.css
src/legal-officer/Home.test.tsx
src/legal-officer/Home.tsx
src/legal-officer/__snapshots__/Home.test.tsx.snap
src/legal-officer/transaction-protection/PendingLocRequests.tsx
src/legal-officer/transaction-protection/RejectedLocRequests.tsx
src/wallet-user/Home.css
src/wallet-user/Home.tsx
src/wallet-user/transaction-protection/RejectedLocs.tsx
src/wallet-user/transaction-protection/RequestedLocs.tsx
src/wallet-user/transaction-protection/__snapshots__/RejectedLocs.test.tsx.snap
src/wallet-user/transaction-protection/__snapshots__/RequestedLocs.test.tsx.snap

logion-network/logion-internal#448
logion-network/logion-internal#449

chore: uniformize dashboard layout; add tooltip to descriptions.

---

src/loc/ContextualizedLocDetails.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap

logion-network/logion-internal#444

chore: change "requested by" to "legal officer in charge" in LOC fot user

---

src/loc/statement/PathModel.ts
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsForm.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

logion-network/logion-internal#468

feat: allow user to select an image to render in SOF.

---

src/common/ViewFileButton.tsx
src/loc/FileModel.ts
src/loc/Model.tsx
src/settings/Files.css
src/settings/Files.tsx
src/settings/SettingsPane.tsx
src/settings/__snapshots__/SettingsPane.test.tsx.snap

logion-network/logion-internal#476

feat: allow LO to upload/download well-known files.

---

src/loc/statement/PrerequisiteWizard.tsx
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsForm.css
src/loc/statement/StatementOfFactsForm.tsx

logion-network/logion-internal#465

feat: add previous to SOF form; report storage error.

---

src/common/AccountInfo.test.tsx
src/common/AccountInfo.tsx
src/common/ComparableField.test.tsx
src/common/ComparableField.tsx
src/common/Identity.test.tsx
src/common/Identity.tsx
src/common/PostalAddress.test.tsx
src/common/PostalAddress.tsx
src/legal-officer/PendingProtectionRequests.tsx
src/legal-officer/RecoveryDetails.test.tsx
src/legal-officer/RecoveryDetails.tsx
src/legal-officer/Types.ts

logion-network/logion-internal#489

fix: show diff with missing protection on recovery.

---

src/common/CommonContext.tsx
src/common/api.tsx

logion-network/logion-internal#483

fix: ignore LOs with no node set.

---

package.json
yarn.lock

logion-network/logion-internal#498

chore: upgrade logion-api.

---

src/wallet-user/trust-protection/ProtectionRefusal.css
src/wallet-user/trust-protection/ProtectionRefusal.tsx

logion-network/logion-internal#493
logion-network/logion-internal#500

feat: improve refusal box layout.

---

src/common/Storage.ts
src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/LegalOfficerPaths.tsx
src/loc/statement/StatementOfFacts.tsx
src/loc/statement/StatementOfFactsButton.tsx

logion-network/logion-internal#507

fix: local storage with SoF.

---

src/legal-officer/RecoveryDetails.tsx
src/loc/CloseLocButton.tsx
src/wallet-user/trust-protection/CreateProtectionRequestForm.test.tsx
src/wallet-user/trust-protection/CreateProtectionRequestForm.tsx
src/wallet-user/trust-protection/ProtectionRecoveryRequest.tsx
src/wallet-user/trust-protection/Recovery.tsx
src/wallet-user/trust-protection/RecoveryRefusal.css
src/wallet-user/trust-protection/RecoveryRefusal.tsx
src/wallet-user/trust-protection/TrustProtection.tsx
src/wallet-user/trust-protection/__snapshots__/CreateProtectionRequestForm.test.tsx.snap
yarn.lock

* feat: add recovery refusal (cancel, resubmit).
* feat: prevent error in case of double recovery vouch.
* feat: protection request: link Next button to agree checkbox.
logion-network/logion-internal#500

feat: add recovery refusal (cancel, resubmit).

---

src/wallet-user/trust-protection/Officer.tsx
src/wallet-user/trust-protection/ProtectionRefusal.tsx
src/wallet-user/trust-protection/SelectLegalOfficer.tsx

logion-network/logion-internal#493

feat: fix LLO details spacing.

---

src/wallet-user/UserContext.tsx

logion-network/logion-internal#522

fix: refresh LOC state.

---

package.json
src/certificate/Certificate.css
src/certificate/Certificate.tsx
src/certificate/CertificateCell.tsx
src/common/FileSelectorButton.css
src/common/InlineDateTime.tsx
src/loc/ImportItemDetails.css
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.css
src/loc/ImportItems.tsx
src/loc/UserContextualizedLocDetails.tsx
yarn.lock

logion-network/logion-internal#528

feat: enable item file upload.

---

package.json
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx
yarn.lock

logion-network/logion-internal#511

feat: strengthen CSV validity check.

---

src/common/FileSelectorButton.css
src/loc/ImportItemDetails.css
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.css
src/loc/ImportItems.tsx

logion-network/logion-internal#511

feat: better handling of upload failure.

---

craco.config.js
package.json
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.tsx
yarn.lock

logion-network/logion-internal#533

feat: use new SDK version for upload.

---

package.json
src/certificate/Certificate.test.tsx
src/certificate/MetaMaskClaimButton.test.tsx
src/certificate/MetaMaskClaimButton.tsx
src/certificate/__snapshots__/MetaMaskClaimButton.test.tsx.snap
src/logion-chain/LogionChainContext.tsx
src/logion-chain/Signature.tsx
src/logion-chain/__mocks__/LogionChainMock.ts
yarn.lock

logion-network/logion-internal#535

feat: adapt MetaMaskClaimButton to authenticate instead of simply signing.

---

src/certificate/CollectionItemCellRow.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/statement/SofParams.ts
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

logion-network/logion-internal#541

feat: show files and token in cert and sof.

---

src/loc/ContextualizedLocDetails.tsx
src/loc/LocDetails.test.tsx
src/loc/LocItemDetail.test.tsx
src/loc/LocItemDetail.tsx
src/loc/LocItems.test.tsx
src/loc/LocItems.tsx
src/loc/LocPrivateFileButton.test.tsx
src/loc/LocPrivateFileButton.tsx
src/loc/LocPrivateFileDetails.test.tsx
src/loc/LocPrivateFileForm.tsx
src/loc/LocPublicDataButton.test.tsx
src/loc/LocPublicDataButton.tsx
src/loc/LocPublicDataDetails.test.tsx
src/loc/LocPublicDataDetails.tsx
src/loc/LocPublishButton.test.tsx
src/loc/LocPublishButton.tsx
src/loc/LocPublishPublicDataButton.test.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__mocks__/UserLocContextMock.tsx
src/loc/__snapshots__/LocDetails.test.tsx.snap
src/loc/__snapshots__/LocItemDetail.test.tsx.snap
src/loc/__snapshots__/LocItems.test.tsx.snap
src/loc/__snapshots__/LocPrivateFileDetails.test.tsx.snap
src/loc/__snapshots__/LocPublicDataDetails.test.tsx.snap
src/loc/__snapshots__/LocPublishPublicDataButton.test.tsx.snap
src/tests.tsx

logion-network/logion-internal#204

chore: add missing unit tests.

---

package.json
src/loc/ImportItems.tsx
yarn.lock

logion-network/logion-internal#555

Enhance support for multiple token types

---

src/common/CopyPasteButton.css
src/common/Table.css
src/components/itemfiles/ItemFileDetails.css
src/components/itemfiles/ItemFileDetails.tsx
src/components/itemfiles/ItemFiles.css
src/components/itemfiles/ItemFiles.test.tsx
src/components/itemfiles/ItemFiles.tsx
src/components/itemfiles/ItemFilesDetails.test.tsx
src/components/itemfiles/__snapshots__/ItemFiles.test.tsx.snap
src/components/itemfiles/__snapshots__/ItemFilesDetails.test.tsx.snap
src/components/table/CellWithCopyPaste.test.tsx
src/components/table/CellWithCopyPaste.tsx
src/components/table/__snapshots__/CellWithCopyPaste.test.tsx.snap
src/loc/CollectionLocItemChecker.css
src/loc/CollectionLocItemChecker.test.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/FileModel.ts
src/loc/UserContextualizedLocDetails.tsx

logion-network/logion-internal#562

Add delivery history

---

src/components/deliverycheck/CheckDeliveredButton.tsx
src/components/itemfiles/ItemFiles.test.tsx
src/components/itemfiles/ItemFilesDetails.test.tsx
src/components/itemfiles/__snapshots__/ItemFilesDetails.test.tsx.snap
src/loc/FileModel.ts

logion-network/logion-internal#562

Handle ownership check result

---

package.json
src/__mocks__/@logion/client.ts
src/__mocks__/@logion/node-api/index.ts
src/__mocks__/LogionClientMock.ts
src/certificate/Certificate.test.tsx
src/certificate/Certificate.tsx
src/certificate/CollectionItemCellRow.tsx
src/certificate/IntroductionText.tsx
src/certificate/LegalOfficerRow.tsx
src/common/Model.tsx
src/components/deliverycheck/CheckDeliveredButton.test.tsx
src/components/deliverycheck/CheckDeliveredButton.tsx
src/components/deliverycheck/CheckDeliveredDialog.tsx
src/components/deliverycheck/CheckDeliveredFrame.tsx
src/components/itemfiles/ItemFileDetails.tsx
src/components/itemfiles/ItemFiles.test.tsx
src/components/itemfiles/ItemFiles.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/UserContextualizedLocDetails.tsx
src/logion-chain/__mocks__/LogionChainMock.ts
yarn.lock

logion-network/logion-internal#562

feat: use new API.

---

src/components/identity/IdentityLocRequest.tsx
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap

logion-network/logion-internal#574

feat: improve style/wording of  identity request.

---

src/ExtrinsicSubmitter.tsx
src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/LegalOfficerContext.tsx
src/legal-officer/LegalOfficerData.ts
src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/__mocks__/LegalOfficerContext.tsx
src/legal-officer/__mocks__/LegalOfficerContextMock.tsx
src/legal-officer/__snapshots__/ContextualizedWallet.test.tsx.snap
src/legal-officer/__snapshots__/LegalOfficerRouter.test.tsx.snap
src/logion-chain/LogionChainContext.tsx
src/logion-chain/__mocks__/LogionChainMock.ts
src/settings/ChainData.css
src/settings/ChainData.test.tsx
src/settings/ChainData.tsx
src/settings/DirectoryData.test.tsx
src/settings/DirectoryData.tsx
src/settings/Settings.tsx
src/settings/SettingsPane.css
src/settings/SettingsPane.test.tsx
src/settings/SettingsPane.tsx
src/settings/__snapshots__/SettingsPane.test.tsx.snap
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap

- If on-chain settings are not properly filled-in, a warning dialog pops up (in the same way as for the user when not protected yet)
- The base URL setting was moved from directory data panel to the chain data panel
- The content of `LegalOfficerData.ts` file will be moved to `logion/node-api` once the feature is considered as "done".
logion-network/logion-internal#575

Enable on-chain settings

---

src/common/TransactionType.tsx
src/common/types/ModelTypes.ts
src/loc/CloseLocButton.tsx
src/loc/ContextualizedLocDetails.css
src/loc/ContextualizedLocDetails.tsx
src/loc/LocContext.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap

* Legal Officer
* Show personal info (user identity and postal address) in Identity LOC management screen.
* Close LOC with seal received from backend.
* Improve layout of VOID buttons.
* User
* View their identity LOCs/

Identity LOC screen

---

src/components/identity/PersonalInfo.tsx
src/loc/CloseLocButton.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/UserContextualizedLocDetails.tsx

logion-network/logion-internal#578

chore: tests feedback.

---

src/certificate/ClaimAssetButton.css
src/certificate/ClaimAssetButton.tsx
src/loc/ImportItems.tsx
src/settings/ValuesFiles.tsx

Depends on PR https://github.com/logion-network/logion-wallet/pull/339

Add spinners on upload

---

src/config/development.json.sample
src/config/index.tsx
src/loc/ImportCsvReader.test.ts
src/loc/ImportCsvReader.ts
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx

logion-network/logion-internal#588

Add Terms and Conditions to csv import.

---

src/settings/ValuesFiles.tsx

* Move spinner at the right place
logion-network/logion-internal#598

Fix settings upload spinner

---

src/certificate/LogionClassification.tsx
src/certificate/LogionTerms.css
src/certificate/LogionTerms.tsx
src/certificate/__snapshots__/LogionClassification.test.tsx.snap
src/certificate/__snapshots__/LogionTerms.test.tsx.snap

* Follow provided designs
logion-network/logion-internal#589

Improve T&Cs layout (certificate)

---

public/statement.css
src/PublicPaths.tsx
src/loc/LocContext.tsx
src/loc/statement/SofParams.ts
src/loc/statement/SofTermsAndConditionsEN.tsx
src/loc/statement/SofTermsAndConditionsFR.tsx
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

logion-network/logion-internal#589

Improve T&Cs layout (SoF)

---

package.json
src/certificate/LogionClassification.test.tsx
src/certificate/__snapshots__/LogionClassification.test.tsx.snap
src/loc/ImportItemDetails.css
src/loc/ImportItemDetails.tsx
yarn.lock

logion-network/logion-internal#588

Display terms and conditions on import details screen.

---

package.json
src/certificate/LogionTerms.tsx
src/loc/statement/SofTermsAndConditionsEN.tsx
src/loc/statement/SofTermsAndConditionsFR.tsx
yarn.lock

logion-network/logion-internal#601

feat: transferred rights displayed in French in SOF.

---

src/certificate/Certificate.test.tsx
src/certificate/Certificate.tsx

* Fixes the issue below
* Adds some tests
logion-network/logion-internal#609

Hide asset check with no restricted delivery

---

package.json
src/wallet-user/UserRouter.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap
src/wallet-user/transaction-protection/LocCreation.css
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/transaction-protection/LocCreationForm.tsx
yarn.lock

logion-network/logion-internal#607

Check for identity LOC instead of protection.

---

src/certificate/CollectionItemCellRow.tsx
src/components/certificateitemdetails/CertificateItemDetails.test.tsx
src/components/certificateitemdetails/CertificateItemDetails.tsx
src/components/certificateitemdetails/__snapshots__/CertificateItemDetails.test.tsx.snap
src/components/deliverycheck/CheckDeliveredFrame.tsx
src/components/frametitle/FrameTitle.css
src/components/frametitle/FrameTitle.test.tsx
src/components/frametitle/FrameTitle.tsx
src/components/frametitle/__snapshots__/FrameTitle.test.tsx.snap
src/components/itemfiles/ItemFiles.css
src/components/itemfiles/ItemFiles.test.tsx
src/components/itemfiles/ItemFiles.tsx
src/components/itemfiles/__snapshots__/ItemFiles.test.tsx.snap
src/loc/CollectionLocItemChecker.test.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/DashboardCertificate.css
src/loc/DashboardCertificate.test.tsx
src/loc/DashboardCertificate.tsx
src/loc/FileModel.ts
src/loc/UserContextualizedLocDetails.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__snapshots__/DashboardCertificate.test.tsx.snap

* Add item data (same as certificate)
* Enable item source (i.e. original) file download
logion-network/logion-internal#615

Complete dashboard certificate for items

---

src/legal-officer/transaction-protection/PendingLocRequests.test.tsx
src/legal-officer/transaction-protection/PendingLocRequests.tsx
src/legal-officer/transaction-protection/__snapshots__/PendingLocRequests.test.tsx.snap
yarn.lock

logion-network/logion-internal#607

Add link from pending request to Identity LOC

---

src/__mocks__/LogionClientMock.ts
src/common/types/Accounts.tsx
src/legal-officer/LegalOfficerContext.tsx
src/logion-chain/LogionChainContext.tsx
src/settings/DirectoryData.tsx
src/settings/Settings.tsx
src/settings/SettingsPane.tsx
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap
yarn.lock

* Re-enable setup of new LLO (only if already registered on-chain).
logion-network/logion-internal#617

Enable activation of LLO

---

public/license/LIRC-v1.0.txt
src/certificate/LogionClassification.tsx
src/certificate/__snapshots__/LogionClassification.test.tsx.snap
yarn.lock

logion-network/logion-internal#619

Rename and change logion classification

---

src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/trust-protection/IdentityLocRequest.test.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap

* prevent user from requesting identity LOC to legal officers who already have a valid identity LOC.
logion-network/logion-internal#626

One Identity LOC per wallet user

---

package.json
src/common/AccountInfo.test.tsx
src/common/Identity.test.tsx
src/common/TestData.ts
src/common/UserInfo.test.tsx
src/common/UserInfo.tsx
src/common/__snapshots__/UserInfo.test.tsx.snap
src/components/identity/IdentityForm.tsx
src/components/identity/IdentityFormTestHelper.tsx
src/components/identity/IdentityLocRequestDetails.tsx
src/components/identity/PersonalInfo.tsx
src/components/identity/__snapshots__/IdentityLocRequestDetails.test.tsx.snap
src/config/development.json.sample
src/legal-officer/TestData.tsx
src/legal-officer/__snapshots__/PendingProtectionRequests.test.tsx.snap
src/legal-officer/__snapshots__/ProtectedUsers.test.tsx.snap
src/legal-officer/__snapshots__/ProtectionRequestsHistory.test.tsx.snap
src/loc/LocCreationDialog.test.tsx
src/loc/LocCreationDialog.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/DashboardCertificate.test.tsx.snap
src/loc/__snapshots__/LocLinkButton.test.tsx.snap
src/settings/DirectoryData.tsx
src/wallet-user/trust-protection/CreateProtectionRequestForm.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx
src/wallet-user/trust-protection/__snapshots__/CreateProtectionRequestForm.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/ProtectionRecoveryRequest.test.tsx.snap
yarn.lock

* Company checkbox only appears when creating an identity LOC, the protection request case will be handled in a later sprint.
* Very simple UI, will be adjusted with designs yet to be delivered.
logion-network/logion-internal#628

Add company checkbox

---

src/common/CommonContext.tsx
src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/LegalOfficerContext.tsx
src/legal-officer/__mocks__/LegalOfficerContextMock.tsx
src/logion-chain/LogionChainContext.tsx
src/settings/ChainData.tsx
src/settings/DirectoryData.test.tsx
src/settings/DirectoryData.tsx

* Now a LLO which filled-in all required data (and saved them) is able to use the app without any explicit refresh of the page

Streamline LLO onboarding

---

src/certificate/Certificate.tsx
src/certificate/CollectionItemCellRow.css
src/certificate/CollectionItemCellRow.tsx
src/components/checkfileframe/CheckFileFrame.test.tsx
src/components/checkfileframe/CheckFileFrame.tsx
src/components/checkfileframe/__snapshots__/CheckFileFrame.test.tsx.snap
src/components/itemfiles/ItemFiles.tsx
src/components/itemfiles/__snapshots__/ItemFiles.test.tsx.snap
src/loc/ContextualizedLocDetails.tsx
src/loc/DashboardCertificate.css
src/loc/DashboardCertificate.tsx
src/loc/UserContextualizedLocDetails.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
yarn.lock

* Existing *Document conformity check tool* in Collection Item certificate now also checks  item file hash.
* A new *Document conformity check tool* is added to the Collection Item dashboard.

Add Collection Item File Hash Check

---

package.json
public/statement.css
src/certificate/CreativeCommons.css
src/certificate/CreativeCommons.test.tsx
src/certificate/CreativeCommons.tsx
src/certificate/LogionClassification.test.tsx
src/certificate/LogionClassification.tsx
src/certificate/TermsAndConditions.tsx
src/certificate/__snapshots__/CreativeCommons.test.tsx.snap
src/certificate/__snapshots__/LogionClassification.test.tsx.snap
src/certificate/__snapshots__/TermsAndConditions.test.tsx.snap
src/components/license/CreativeCommonsIcon.test.tsx
src/components/license/CreativeCommonsIcon.tsx
src/components/license/__snapshots__/CreativeCommonsIcon.test.tsx.snap
src/config/index.tsx
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx
src/loc/statement/SofParams.ts
src/loc/statement/SofTermsAndConditionsEN.tsx
src/loc/statement/SofTermsAndConditionsFR.tsx
src/loc/statement/StatementOfFacts.tsx
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx
yarn.lock

* Import via CSV.
* Display in certificate and dashboard.
* Display in Statement of facts.

Add Creative Commons

---

src/loc/LocDetailsTab.tsx
src/loc/LocItems.tsx
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/trust-protection/IdentityLocRequest.test.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx

* This PR depends on https://github.com/logion-network/logion-wallet/pull/368 on will remain draft as long as the other PR is not merged
* Identity LOC is created as draft
* Some action buttons are hidden from LO in review mode (delete item, publish item, close LOC)

Draft mode for Identity LOCs

---

src/certificate/CreativeCommons.tsx
src/certificate/__snapshots__/CreativeCommons.test.tsx.snap
src/common/NewTabLink.tsx
src/components/license/CreativeCommonsIcon.css
src/components/license/CreativeCommonsIcon.test.tsx
src/components/license/CreativeCommonsIcon.tsx
src/components/license/__snapshots__/CreativeCommonsIcon.test.tsx.snap

logion-network/logion-internal#636

Add link under Creative Commons icon.

---

src/legal-officer/transaction-protection/RejectedLocRequests.tsx
src/legal-officer/transaction-protection/VoidLocs.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap

logion-network/logion-internal#605

Handle feedback

---

src/certificate/LogionTerms.test.tsx
src/certificate/__snapshots__/LogionTerms.test.tsx.snap
yarn.lock

Adapt tests (failing due stricter validation rules) to latest version of Logion Classification
See [this PR](https://github.com/logion-network/logion-api/pull/69)
logion-network/logion-internal#640

Adapt tests to new validations rules.

---

src/loc/LocPrivateFileButton.tsx

logion-network/logion-internal#642

Add feedback when hashing file before upload.

---

src/loc/ContextualizedLocDetails.tsx
src/loc/DashboardCertificate.tsx
src/loc/LocContext.tsx
src/wallet-user/UserContext.tsx

* Reject leads to right path
* Items are loaded on closed collection LOC view
* NFT asset check is hidden in dashboard certificate if no restricted delivery is configured
* Fixed some "State discarded" errors
logion-network/logion-internal#624

Various fixes on draft mode feature

---

public/statement.css
src/loc/statement/SofTermsAndConditionsEN.tsx
src/loc/statement/SofTermsAndConditionsFR.tsx

Creative Commons URL appears textually in SOF.
logion-network/logion-internal#636

feat: add CC textual url in SOF.

---

src/loc/LocDetailsTab.tsx
src/loc/LocLinkButton.test.tsx
src/loc/LocLinkButton.tsx
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/loc/__snapshots__/LocLinkButton.test.tsx.snap

logion-network/logion-internal#657

feat: remove "Link to a new Identity|Transaction LOC" options.

---

package.json
src/ClientExtrinsicSubmitter.tsx
src/ExtrinsicSubmissionResult.test.tsx
src/ExtrinsicSubmissionResult.tsx
src/ExtrinsicSubmitter.test.tsx
src/ExtrinsicSubmitter.tsx
src/__mocks__/@logion/client.ts
src/__mocks__/LogionClientMock.ts
src/legal-officer/PendingProtectionRequests.test.tsx
src/legal-officer/RecoveryDetails.test.tsx
src/loc/LocContext.tsx
src/logion-chain/LogionChainContext.tsx
src/logion-chain/__mocks__/SignatureMock.tsx
src/logion-chain/index.tsx
yarn.lock

* We switch back to waiting for finalization before considering a submission as successful.

Use default sign and send strategy

---

src/__mocks__/@logion/client.ts
src/__mocks__/LogionClientMock.ts
src/common/Model.tsx
src/legal-officer/__mocks__/ClientMock.ts
src/legal-officer/__mocks__/client.ts
src/legal-officer/client.ts
src/loc/LegalOfficerLocContext.tsx
src/loc/LocContext.test.tsx
src/loc/LocContext.tsx
src/loc/LocDetailsTab.tsx
src/loc/VoidLocButton.test.tsx
src/loc/VoidLocButton.tsx
src/loc/VoidLocReplaceExistingButton.test.tsx
src/loc/VoidLocReplaceExistingButton.tsx
src/loc/VoidLocReplaceNewButton.test.tsx
src/loc/VoidLocReplaceNewButton.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__mocks__/UserLocContextMock.tsx
src/loc/statement/StatementOfFactsRequestButton.test.tsx
src/loc/statement/StatementOfFactsRequestButton.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/transaction-protection/ClosedLocs.tsx
src/wallet-user/transaction-protection/DraftLocs.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/transaction-protection/OpenedLocs.tsx
src/wallet-user/transaction-protection/RejectedLocs.tsx
src/wallet-user/transaction-protection/RequestedLocs.tsx
src/wallet-user/transaction-protection/VoidLocs.tsx

* Last functions where converted
* It is now possible to tell the context that the whole set of LOCs needs to be updated at the higher level (was necessary for cancel and requestSof functions)
https://github.com/logion-network/logion-internal/issues/643

Simplify LOC context (end)

---

src/ClientExtrinsicSubmitter.tsx
src/common/Frame.tsx
src/common/MultiChoiceButton.css
src/common/MultiChoiceButton.tsx
src/common/__snapshots__/Frame.test.tsx.snap
src/legal-officer/LegalOfficerContext.tsx
src/loc/CloseLocButton.tsx
src/loc/LocContext.tsx
src/loc/LocCreationDialog.tsx
src/loc/LocDetailsTab.tsx
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/wallet-user/trust-protection/Recovery.tsx
src/wallet-user/trust-protection/TrustProtection.tsx

* Close button component is not destroyed anymore upon LOC closing so that implemented processes actually complete
* Recovery details dropdown button style is fixed
* Closing and voiding dates are now properly refreshed
logion-network/logion-internal#660

Fix wallet protection and recovery

---

package.json
src/legal-officer/client.test.ts
src/loc/CloseLocButton.test.tsx
src/loc/CloseLocButton.tsx
src/loc/LocDetailsTab.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/wallet-user/transaction-protection/RejectedLocs.tsx
src/wallet-user/transaction-protection/__snapshots__/RejectedLocs.test.tsx.snap
yarn.lock

* Added cancel and rework actions in rejected LOCs table (WU only)
* Fixed visibility of "add link" and "close" buttons
logion-network/logion-internal#663

Enable cancel or rework of rejected LOC requests

---

yarn.lock

* No code change was needed.
logion-network/logion-internal#656

Upgrade to polkadot-v0.9.31

---

package.json
src/common/__mocks__/ModelMock.ts
src/components/identity/IdentityLocRequestDetails.test.tsx
src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/loc/LocCreationDialog.test.tsx
src/loc/LocCreationSteps.tsx
src/loc/TestData.ts
src/loc/VoidLocReplaceNewButton.test.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
yarn.lock

logion-network/logion-internal#670

feat: accept LOC requests created by LO.

---

src/RootPaths.tsx
src/common/__mocks__/ModelMock.ts
src/components/identity/IdentityLocRequestDetails.test.tsx
src/legal-officer/LegalOfficerPaths.tsx
src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/__mocks__/ClientMock.ts
src/legal-officer/__mocks__/client.ts
src/legal-officer/__snapshots__/LegalOfficerRouter.test.tsx.snap
src/legal-officer/client.ts
src/loc/CertificateAndLimits.tsx
src/loc/TestData.ts
src/loc/__snapshots__/CertificateAndLimits.test.tsx.snap
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/loc/vtp/VTPSelection.tsx
src/loc/vtp/VTPSelectionButton.tsx
src/loc/vtp/VTPSelectionCheckbox.test.tsx
src/loc/vtp/VTPSelectionCheckbox.tsx
src/loc/vtp/VTPSelectionFrame.css
src/loc/vtp/VTPSelectionFrame.test.tsx
src/loc/vtp/VTPSelectionFrame.tsx
src/loc/vtp/VTPSelectionPane.tsx
yarn.lock

* On an Open Transaction or Collection LOC, LO may select a new VTP
* Similarly, LO may remove a previously selected VTP.
logion-network/logion-internal#685

Add VTP selection/un-selection.

---

src/legal-officer/ContextualizedWallet.tsx
src/legal-officer/Home.tsx
src/legal-officer/LegalOfficerPaths.tsx
src/legal-officer/LegalOfficerRouter.tsx
src/legal-officer/__snapshots__/ContextualizedWallet.test.tsx.snap
src/legal-officer/__snapshots__/LegalOfficerRouter.test.tsx.snap
src/loc/CertificateAndLimits.tsx
src/loc/ContextualizedLocDetails.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/vtp/VTPClosedLocs.test.tsx
src/wallet-user/vtp/VTPClosedLocs.tsx
src/wallet-user/vtp/VTPOpenedLocs.test.tsx
src/wallet-user/vtp/VTPOpenedLocs.tsx
src/wallet-user/vtp/VTPUtils.ts
src/wallet-user/vtp/__snapshots__/VTPClosedLocs.test.tsx.snap
src/wallet-user/vtp/__snapshots__/VTPOpenedLocs.test.tsx.snap
yarn.lock

* Wallet user VTP locs are listed.
* LO may also (un)select a VTP on Open (Polkadot) Identity LOC.
* LO Identity LOC URL is streamlined (`/legal-officer/identities` updated to `/legal-officer/loc/identity`)
logion-network/logion-internal#685
logion-network/logion-internal#688

List VTP LOCS - Add Selection button to Polkadot Identity LOC.

---

src/RenderOrRedirectToLogin.test.tsx
src/RenderOrRedirectToLogin.tsx
src/__snapshots__/RenderOrRedirectToLogin.test.tsx.snap
src/logion-chain/__mocks__/LogionChainMock.ts

* Redirects to login page as soon as current user is not authenticated anymore
logion-network/logion-internal#691

Blank page on token expiration

---

src/common/SubmitterName.tsx
src/legal-officer/__mocks__/ClientMock.ts
src/legal-officer/client.ts
src/loc/LocDetailsTab.tsx
src/loc/LocItems.tsx
src/loc/UserContextualizedLocDetails.tsx
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/loc/vtp/VTPSelectionCheckbox.test.tsx
src/loc/vtp/VTPSelectionCheckbox.tsx
src/loc/vtp/VTPSelectionFrame.tsx
yarn.lock

* When VTP, View file button is removed in front of files not contributed by self.
* A Tooltip explains the badge.
* Names of former selected VTP are still shown.

VTP Management improval

---

public/statement.css
src/components/pagedtable/PagedTable.css
src/components/pagedtable/PagedTable.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap
src/loc/statement/SofParams.ts
src/loc/statement/StatementOfFactsButton.css
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

* Adds Request SoF/SoF buttons on each item line in items table
* Adds file deliveries to SoF content
* Fixes paging
* Adds "Import All" button on top of items table (import)
* Refactors `StatementOfFactsButton`
logion-network/logion-internal#694

Add SoF button in items table

---

src/legal-officer/client.ts

logion-network/logion-internal#688

Prevent LO to select requester as a VTP.

---

src/loc/CollectionLocItemChecker.tsx
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap

* Remove redundant SoF button on item check
* Remove buttons column header and move "View" first
logion-network/logion-internal#694

Feedback on US131

---

src/common/SubmitterName.test.tsx
src/common/__snapshots__/SubmitterName.test.tsx.snap
src/legal-officer/client.test.ts

logion-network/logion-internal#688

Add unit tests for VTP-related components.

---

src/loc/statement/SofParams.ts
src/loc/statement/SofTermsAndConditionsEN.tsx
src/loc/statement/SofTermsAndConditionsFR.tsx
src/loc/statement/StatementOfFactsButton.tsx

* Rendering of SoF for an item with a logion classification was broken
* Also properly clears data on cancel

Fix SoF of item with logion classification

---

package.json
src/common/TestData.ts
src/legal-officer/LegalOfficerData.ts
src/loc/__snapshots__/LegalOfficerLocContext.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/logion-chain/__mocks__/LogionChainMock.ts
src/settings/DirectoryData.tsx
src/wallet-user/trust-protection/__snapshots__/CreateProtectionRequestForm.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/ProtectionRecoveryRequest.test.tsx.snap
yarn.lock

* Goal: prevent frontend crashes in the host case, explicit support for guests will come later
logion-network/logion-internal#699

Upgrade logion dependencies

---

src/legal-officer/client.ts
yarn.lock

* Fixes bug as well as a dependabot alert
logion-network/logion-internal#696

Fix error on close in case of concurrent refresh

---

src/legal-officer/Votes.tsx
src/legal-officer/client.ts

* Retrieves votes from backend (result of sync).

Take votes from backend

---

package.json
src/legal-officer/client.ts
src/loc/RequestVoteButton.tsx
yarn.lock

logion-network/logion-internal#726

Call vote node-api method.

---

src/certificate/Certificate.css
src/certificate/Certificate.tsx
src/certificate/ClaimAssetButton.test.tsx
src/certificate/ClaimAssetButton.tsx
src/certificate/CollectionItemCellRow.tsx
src/certificate/__snapshots__/ClaimAssetButton.test.tsx.snap
src/loc/FileModel.ts
src/loc/ImportCsvReader.test.ts
src/loc/ImportCsvReader.ts
src/loc/ImportItems.tsx
src/loc/RestrictedDeliveryCell.css

* Add claim button for collection files with restricted delivery in item certificate.
logion-network/logion-internal#735

Add claim document button to certificate

---

src/certificate/Certificate.tsx
src/components/checkfileframe/CheckFileFrame.tsx
src/components/checkfileframe/__snapshots__/CheckFileFrame.test.tsx.snap
src/components/deliverycheck/CheckDeliveredFrame.tsx
src/components/itemfiles/ItemFiles.tsx
yarn.lock

* Check hash against delivered collection file.
* Re-enable expand button in collection item files.
logion-network/logion-internal#738
logion-network/logion-internal#758

Check hash against delivered collection file

---

src/certificate/CertificateCell.css
src/certificate/CollectionItemCellRow.css
src/common/NewTabLink.tsx
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLocItemChecker.css
src/loc/DashboardCertificate.css
src/loc/LocPane.css
src/loc/__snapshots__/CertificateAndLimits.test.tsx.snap

* Matched items are now in a solid green box (previously, was dotted pink).
* Developer settings refer correct documentation.
logion-network/logion-internal#757

Miscellaneous improvements

---

src/certificate/Authenticate.css
src/certificate/Authenticate.test.tsx
src/certificate/Authenticate.tsx
src/certificate/Certificate.tsx
src/certificate/ClaimAssetButton.css
src/certificate/ClaimAssetButton.test.tsx
src/certificate/ClaimAssetButton.tsx
src/certificate/CollectionItemCellRow.tsx
src/certificate/IntroductionText.tsx
src/certificate/__snapshots__/Authenticate.test.tsx.snap
src/common/ViewFileButton.tsx
src/loc/FileModel.ts
src/logion-chain/LogionChainContext.tsx

* Split authentication and download on collection item certificate.
logion-network/logion-internal#767

Token-gated Certificate

---

src/loc/FileModel.test.ts
src/loc/FileModel.ts

* Remove useless check resources.
* Test isTokenOwner().
logion-network/logion-internal#775

Remove useless check resources.

---

package.json
src/common/TransactionType.tsx
src/components/identity/IdentityLocRequestDetails.test.tsx
src/legal-officer/__mocks__/ClientMock.ts
src/legal-officer/client.test.ts
src/legal-officer/client.ts
src/loc/vtp/Nominate.tsx
src/loc/vtp/VTPSelectionCheckbox.test.tsx
src/loc/vtp/VTPSelectionCheckbox.tsx
src/loc/vtp/VTPSelectionFrame.tsx
yarn.lock

* Nomination/dismissal/selection/unselection are now on-chain operations.
logion-network/logion-internal#765

Use on-chain issuers

---

src/certificate/Certificate.tsx
src/certificate/ClaimAssetButton.tsx
src/certificate/CollectionItemCellRow.tsx
src/certificate/TokensRecords.css
src/certificate/TokensRecords.tsx
src/loc/FileModel.ts
yarn.lock

* Tokens records are shown on the certificate.
* The related files can be downloaded when user is authenticated.
logion-network/logion-internal#780

Add tokens records to certificate.

---

src/certificate/CertificateTitle.css
src/loc/LocPublicDataForm.tsx
src/loc/LocTemplateItems.tsx

* Second feedback wave starts here: https://github.com/logion-network/logion-internal/issues/734#issuecomment-1452201371
logion-network/logion-internal#734

Handle test feedback (2)

---

src/__mocks__/@logion/client.ts
src/certificate/Authenticate.tsx
yarn.lock

* Decision of which wallet to propose to the user is done based on network type.
* See https://github.com/logion-network/logion-api/pull/111
logion-network/logion-internal#793

Decide which wallet to present to user according to network type.

---

public/assets/qr.svg
src/certificate/Certificate.tsx
src/certificate/IntroductionText.tsx
src/loc/CertificateAndLimits.css
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLocItemChecker.css
src/loc/CollectionLocItemChecker.tsx
src/loc/ViewCertificateButton.css
src/loc/ViewCertificateButton.test.tsx
src/loc/ViewCertificateButton.tsx
src/loc/ViewQrCodeButton.css
src/loc/ViewQrCodeButton.test.tsx
src/loc/ViewQrCodeButton.tsx
src/loc/__snapshots__/CertificateAndLimits.test.tsx.snap
src/loc/__snapshots__/ViewCertificateButton.test.tsx.snap

* Certificate was adjusted given specifications.
* QR code can be displayed in the dashboard.
logion-network/logion-internal#810

QR code (continued)

---

src/certificate/Authenticate.css
src/certificate/Authenticate.tsx
src/certificate/IntroductionText.tsx
src/certificate/__snapshots__/Authenticate.test.tsx.snap
src/common/ButtonGroup.css
src/common/CopyPasteButton.tsx
src/loc/CertificateAndLimits.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/ViewCertificateButton.tsx
src/loc/ViewQrCodeButton.tsx
src/loc/__snapshots__/CertificateAndLimits.test.tsx.snap
src/loc/__snapshots__/ViewCertificateButton.test.tsx.snap

* Handle feedback starting here: https://github.com/logion-network/logion-internal/issues/807#issuecomment-1458102975
logion-network/logion-internal#807

chore: handle feedback.

---

package.json
src/__mocks__/@logion/node-api/dist/LogionLocMock.ts
src/legal-officer/client.ts
src/loc/LocContext.test.tsx
src/loc/LocItem.tsx
src/loc/LocItemFactory.ts
src/loc/LocItems.test.tsx
src/loc/LocPublishPrivateFileButton.tsx
src/loc/TestData.ts
yarn.lock

* Add size when publishing LOC file.
* Upgrade @logion/extension (Upgrade of Polkadot).
logion-network/logion-internal#822

Add size when publishing LOC file.

---

src/common/Model.tsx
src/legal-officer/LegalOfficerContext.tsx
yarn.lock

* Use optimized SDK.
* Batch-fetch protection requests and vault transfer requests (LLO).
logion-network/logion-internal#828

Improve batch fetching

---

src/common/TestData.ts
src/common/TransactionStatusCell.test.tsx
src/common/TransactionStatusCell.tsx
src/common/TransferAmountCell.tsx
src/common/__snapshots__/TransactionStatusCell.test.tsx.snap
src/legal-officer/Home.tsx
src/legal-officer/__snapshots__/Home.test.tsx.snap
src/loc/EstimatedFees.css
src/loc/EstimatedFees.test.tsx
src/loc/EstimatedFees.tsx
src/loc/LocItem.tsx
src/loc/LocPublishButton.test.tsx
src/loc/LocPublishButton.tsx
src/wallet-user/Home.tsx
yarn.lock

logion-network/logion-internal#831

Show fees breakdown in transactions

---

src/loc/EstimatedFees.tsx
src/loc/LocItem.tsx
src/loc/LocItemDetails.css
src/loc/LocItemFactory.ts
src/loc/LocLinkDetails.tsx
src/loc/LocPrivateFileDetails.test.tsx
src/loc/LocPrivateFileDetails.tsx
src/loc/LocPublicDataDetails.tsx
src/loc/record/TokensRecordTable.tsx
yarn.lock

* Paid fees are exposed in LOC item details
* Storage fees are annotated with a "paid by" comment telling who actually paid them (owner or requester)
logion-network/logion-internal#831

Show paid fees in LOC item details

---

public/assets/polkadot-account-white.svg
public/assets/polkadot-account.svg
src/common/AccountAddress.css
src/common/AccountAddress.tsx
src/common/CommonContext.tsx
src/common/Model.tsx
src/common/__mocks__/ModelMock.ts
src/common/__snapshots__/AccountAddress.test.tsx.snap
src/legal-officer/client.ts
src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/loc/LocCreationDialog.test.tsx
src/loc/LocCreationDialog.tsx
src/loc/LocCreationSteps.tsx
src/loc/VoidLocReplaceNewButton.tsx
src/logion-chain/LogionChainContext.tsx
src/tests.tsx
src/wallet-user/ContextualizedWallet.test.tsx
src/wallet-user/ContextualizedWallet.tsx
src/wallet-user/UserContext.tsx
src/wallet-user/UserRouter.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx
yarn.lock

* Metamask address are now taken into account at login.
* It is possible for a Metamask user to create an Identity LOC and submit it to a LLO.
logion-network/logion-internal#852

Identity LOC creation with Metamask

---

package.json
src/common/TransactionType.tsx
src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/loc/LocCreationSteps.tsx
src/loc/LocDetailsTab.tsx
src/loc/RequesterOrLegalOfficer.tsx
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/loc/__snapshots__/RequesterOrLegalOfficer.test.tsx.snap
src/wallet-user/trust-protection/IdentityLocRequest.css
src/wallet-user/trust-protection/IdentityLocRequest.tsx
yarn.lock

* Other ID LOC requester must provide a sponsorship ID
* The sponsorship ID is shown in the UI
* As this is only implemented for testing purpose, there is no validation on the sponsorship itself (i.e. there is no check on the fact that the sponsorship targets the right requester and LLO)
logion-network/logion-internal#861

Enable sponsoring

---

src/certificate/Authenticate.test.tsx
src/certificate/Authenticate.tsx
src/certificate/CollectionItemCellRow.tsx
src/certificate/__snapshots__/Authenticate.test.tsx.snap
src/components/certificateitemdetails/CertificateItemDetails.test.tsx
src/components/certificateitemdetails/CertificateItemDetails.tsx
src/components/certificateitemdetails/__snapshots__/CertificateItemDetails.test.tsx.snap

* Feature: Hide the confusing message "Restricted Delivery: No" on Collection item certificate.
* Fix: The entry "with Polkadot" was missing from drop-down list of "Connect & claim" button. 
logion-network/logion-internal#882

Restricted Delivery Improvement

---

src/loc/IdenfyVerification.tsx
src/wallet-user/IdenfyVerificationResult.tsx
src/wallet-user/UserRouter.tsx

* Provide resume urls when starting an iDenfy verification process.
* Companion of https://github.com/logion-network/logion-backend-ts/pull/242
logion-network/logion-internal#884

iDenfy: Provide resume urls.

---

package.json
src/common/CommonContext.tsx
src/loc/IdenfyVerification.tsx
yarn.lock

* Moved all iDenfy logic to SDK.
* This enables its use by the IDLOC gateway.
logion-network/logion-internal#886

Move iDenfy to SDK

---

src/loc/LocContext.test.tsx
src/loc/LocContext.tsx
src/loc/LocDetailsTab.tsx
src/loc/LocItem.tsx
yarn.lock

* Fixes bug logion-network/logion-internal#870
* Makes use of https://github.com/logion-network/logion-api/commit/8b91d10920e3785cb6124c989582e790a17c812b

Fix LOC display with external links

---

src/common/AmountControl.tsx
src/common/AmountFormat.tsx
src/common/PendingVaultTransferRequests.tsx
src/common/TransferAmountCell.tsx
src/common/WalletGauge.tsx
src/loc/EstimatedFees.tsx
src/vault/VaultOutRequest.tsx
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
yarn.lock

* Consequence of https://github.com/logion-network/logion-internal/issues/842
* Some parts of the code were still using deprecated API elements

Fix following deprecated removal

---

src/__mocks__/LogionMock.ts
src/legal-officer/transaction-protection/LocRequestAcceptance.test.tsx
src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/loc/AcceptRejectLocRequest.test.tsx
src/loc/EstimatedFees.css
src/loc/EstimatedFees.tsx
src/loc/LocItem.tsx
src/loc/LocItemDetails.css
src/loc/LocItemEstimatedFees.tsx
src/loc/LocItemFactory.ts
src/loc/LocItems.test.tsx
src/loc/LocItems.tsx
src/loc/LocLinkDetails.tsx
src/loc/LocPrivateFileDetails.test.tsx
src/loc/LocPrivateFileDetails.tsx
src/loc/LocPublicDataDetails.tsx
src/loc/LocPublishButton.tsx
src/loc/LocTemplateItems.tsx
src/loc/VoidLocReplaceNewButton.test.tsx
src/loc/__snapshots__/AcceptRejectLocRequest.test.tsx.snap
src/loc/__snapshots__/LocItems.test.tsx.snap
src/loc/record/TokensRecordTable.tsx
yarn.lock

* Add legal fee row in fees table.
logion-network/logion-internal#895

Expose legal fees

---

src/legal-officer/transaction-protection/LocRequestAcceptance.tsx
src/loc/LocItem.tsx
src/loc/LocItems.tsx
src/loc/LocTemplateItems.tsx

* Show fees estimates for collection LOCs
* Hide review buttons on template items of pending LOCs
logion-network/logion-internal#892

Handle test feedback

---

src/legal-officer/client.ts
src/loc/LocCreationDialog.test.tsx
src/loc/LocCreationSteps.tsx
src/loc/TestData.ts
src/loc/VoidLocReplaceNewButton.test.tsx
src/loc/VoidLocReplaceNewButton.tsx

* "Void and replace" was only voiding, not replacing (replacing LOC was created but not "linked").

Fix void replace

---

src/loc/LocItemFactory.ts

* Status field of published link items was not properly set.

LOC closing with links

---

src/loc/ImportItems.tsx

* In some cases, app crashed after successful item import.
logion-network/logion-internal#920

Fix crash on item import

---

package.json
src/__mocks__/@logion/client.ts
src/__mocks__/LogionMock.ts
src/common/hash.ts
src/legal-officer/client.ts
src/loc/AcknowledgeButton.tsx
src/loc/ImportCsvReader.ts
src/loc/LocContext.test.tsx
src/loc/LocItem.tsx
src/loc/LocItemFactory.ts
src/loc/LocItems.test.tsx
src/loc/LocPublishLinkButton.tsx
src/loc/LocPublishPrivateFileButton.tsx
src/loc/LocPublishPublicDataButton.tsx
src/loc/TestData.ts
src/loc/types.ts
yarn.lock

* Use new client using `Hash` instead of `string` for published attributes. (see https://github.com/logion-network/logion-api/pull/161)
* Use `nameHash` as a key to for Metadata. (see https://github.com/logion-network/logion-api/pull/162)
logion-network/logion-internal#930

Deletable Public Data

---

src/components/certificateitemdetails/CertificateItemDetails.test.tsx
src/components/certificateitemdetails/CertificateItemDetails.tsx
src/components/certificateitemdetails/__snapshots__/CertificateItemDetails.test.tsx.snap
src/loc/ImportCsvReader.test.ts
src/loc/ImportCsvReader.ts
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.tsx
yarn.lock

* Expects token issuance in CSV import file
* Token issuance is shown on certificate and in dashboard
logion-network/logion-internal#932

Add token issuance

---

src/__mocks__/LogionClientMock.ts
src/common/TransactionStatusCell.tsx
src/legal-officer/__mocks__/ClientMock.ts
src/legal-officer/__mocks__/client.ts
src/legal-officer/client.test.ts
src/legal-officer/client.ts
src/loc/CollectionLocItemChecker.test.tsx
src/loc/LocContext.test.tsx
src/loc/LocContext.tsx
src/loc/LocItem.tsx
src/loc/LocItemFactory.ts
src/loc/LocItems.test.tsx
src/loc/LocLinkExistingLocDialog.tsx
src/loc/LocPublishButton.test.tsx
src/loc/LocPublishLinkButton.tsx
src/loc/VoidLocButton.test.tsx
src/loc/VoidLocButton.tsx
src/loc/VoidLocReplaceExistingButton.test.tsx
src/loc/VoidLocReplaceExistingButton.tsx
src/loc/fees/EstimatedFees.test.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/165
* Aligns with new `Fees` constructor parameters
logion-network/logion-internal#941

Use new LO link and void API

---

src/__mocks__/@logion/node-api/index.ts
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx
src/loc/LocPublishLinkButton.tsx
src/loc/fees/EstimatedFees.test.tsx
src/loc/fees/EstimatedFees.tsx
src/loc/fees/FeeEstimator.ts
src/loc/fees/__snapshots__/EstimatedFees.test.tsx.snap
yarn.lock

* Add certificate fees to `EstimatedFees` component
* Add confirmation dialog popping-up on each item upload and showing the fees to be paid
logion-network/logion-internal#932

Show fees when importing items

---

package.json
src/loc/ImportItems.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/173
logion-network/logion-internal#952

Handle public data submission

---

package.json
src/__mocks__/LogionMock.ts
src/common/FormGroup.tsx
src/components/identity/CollectionInfo.css
src/components/identity/CollectionInfo.tsx
src/legal-officer/transaction-protection/LocRequestAcceptanceAndCreation.test.tsx
src/loc/LocDetailsTab.tsx
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/loc/fees/EstimatedFees.tsx
src/loc/fees/FeeEstimator.ts
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/transaction-protection/LocCreationForm.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/176
* Request value fee before creating draft collection LOC
* Show value fee above items in LOC details
logion-network/logion-internal#960

Add value fees

---

src/loc/LocItemFactory.ts
src/loc/LocLinkDetails.tsx

logion-network/logion-internal#953

Do not show random ID when link target not set

---

src/__mocks__/LogionMock.ts
src/common/__snapshots__/AddressSwitcher.test.tsx.snap
src/legal-officer/transaction-protection/__snapshots__/PendingLocRequests.test.tsx.snap
src/loc/LocContext.test.tsx
src/loc/LocDetails.test.tsx
src/loc/LocItem.tsx
src/loc/LocItemFactory.ts
src/loc/LocItems.test.tsx
src/loc/LocItems.tsx
src/loc/LocPane.tsx
src/loc/LocTemplateItems.tsx
src/loc/UserContextualizedLocDetails.test.tsx
src/loc/UserContextualizedLocDetails.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/DashboardCertificate.test.tsx.snap
src/loc/__snapshots__/LocDetails.test.tsx.snap
src/loc/__snapshots__/LocPublishLinkButton.test.tsx.snap
src/loc/__snapshots__/LocPublishPrivateFileButton.test.tsx.snap
src/loc/__snapshots__/LocPublishPublicDataButton.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/loc/record/TokensRecordButton.tsx
src/loc/record/TokensRecordTable.tsx
src/loc/types.ts
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap
yarn.lock

* Add verified issuer item publication by requester.
* Add item acknowledge by verified issuer.
logion-network/logion-internal#972

Add Verified Issuer Submission Review

---

src/Login.tsx
src/common/AddressSwitcher.tsx
src/logion-chain/LogionChainContext.tsx
src/wallet-user/Main.tsx

* When switching account, navigate to dashboard in order to prevent access to "forbidden" screens
* Fix login and account management
logion-network/logion-internal#971

Fix manual MetaMask activation and improve account switching

---

src/loc/LocDetailsTab.tsx

logion-network/logion-internal#987

Publication of template items

---

src/certificate/Certificate.test.tsx
src/certificate/Certificate.tsx
src/certificate/__snapshots__/Certificate.test.tsx.snap

logion-network/logion-internal#947

Remove briefly displayed "LOC NOT FOUND" on certificate.

---

src/common/AccountAddress.css
src/common/AccountAddress.test.tsx
src/common/AccountAddress.tsx
src/common/AddressSwitcher.test.tsx
src/common/AddressSwitcher.tsx
src/common/ColorTheme.ts
src/common/Icon.tsx
src/common/TestData.ts
src/common/Transactions.tsx
src/common/Wallet.tsx
src/common/__mocks__/CommonContextMock.ts
src/common/__snapshots__/AccountAddress.test.tsx.snap
src/common/__snapshots__/AddressSwitcher.test.tsx.snap
src/common/__snapshots__/Wallet.test.tsx.snap
src/components/coin/CoinIcon.test.tsx
src/components/coin/CoinIcon.tsx
src/components/coin/CoinName.test.tsx
src/components/coin/CoinName.tsx
src/components/coin/__snapshots__/CoinIcon.test.tsx.snap
src/components/coin/__snapshots__/CoinName.test.tsx.snap
src/legal-officer/Types.ts
src/loc/__snapshots__/ItemImporter.test.tsx.snap
src/wallet-user/Types.ts
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
src/wallet-user/trust-protection/WalletRecoveryProcessTab.tsx

* Show balance in address switcher for selected address.
* Prepare for removal of `iconType` and `iconId` from `node-api`'s `Coin` type.
logion-network/logion-internal#1009

Show balance in address switcher

---

src/loc/CollectionLocItemChecker.tsx
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap

logion-network/logion-internal#946

Import items not refreshing properly

---

src/certificate/Certificate.tsx
src/common/InlineDateTime.tsx
src/common/Table.tsx
src/loc/LocContext.test.tsx
src/loc/LocItem.tsx
src/loc/LocItemFactory.ts
src/loc/LocItems.test.tsx
src/loc/TestData.ts
src/loc/record/TokensRecordTable.tsx
src/loc/statement/StatementOfFactsButton.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/191
logion-network/logion-internal#976

DateTime objects on items

---

src/__mocks__/@logion/client.ts
src/common/Grid.tsx
src/common/Table.tsx
src/loc/AcknowledgeButton.tsx
src/loc/ClearItemButton.tsx
src/loc/CustomItemActions.test.tsx
src/loc/CustomItemActions.tsx
src/loc/DeleteButton.tsx
src/loc/LocItem.tsx
src/loc/LocItems.tsx
src/loc/LocTemplateItems.tsx
src/loc/PublishItemButton.tsx
src/loc/SetItemButton.tsx
src/loc/TemplateItemActions.test.tsx
src/loc/TemplateItemActions.tsx
src/loc/__snapshots__/CustomItemActions.test.tsx.snap
src/loc/__snapshots__/TemplateItemActions.test.tsx.snap

* Adds unit tests for custom/template item actions.
* Refactors actions components.
logion-network/logion-internal#921

Add item actions test and refactor

---

src/loc/ImportItemDetails.css
src/loc/ImportItemDetails.tsx
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx

logion-network/logion-internal#1023

Show certificate URL and QR code on item import

---

src/common/Dialog.css
src/loc/LocTemplateItems.tsx

* Fix dialog overflow.
* Fix template item publish.
logion-network/logion-internal#1032

Various fixes

---

package.json
src/loc/LocItem.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/196
logion-network/logion-internal#1026

Enable review of pending LOC items

---

src/ClientExtrinsicSubmitter.tsx
src/components/blocknone/BlockNone.tsx
src/loc/CustomItemActions.tsx
src/loc/LocPublishLinkButton.tsx
src/loc/LocPublishPrivateFileButton.tsx
src/loc/LocPublishPublicDataButton.tsx
src/loc/RequestVoteButton.test.tsx
src/loc/TemplateItemActions.tsx
src/loc/__snapshots__/CustomItemActions.test.tsx.snap
src/loc/__snapshots__/LocItems.test.tsx.snap
src/loc/__snapshots__/TemplateItemActions.test.tsx.snap
src/wallet-user/trust-protection/CreateProtectionRequestForm.test.tsx
yarn.lock

* Problem and solution are described [here](https://github.com/logion-network/logion-internal/issues/1037#issuecomment-1776763434).
* `BlockNone` component was introduced to hide/show a component without destroying it.
logion-network/logion-internal#1037

Fix concurrent publish

---

src/loc/fees/EstimatedFees.tsx
yarn.lock

* Adds recurrent fees to component.
logion-network/logion-internal#1053

Show recurrent fees in estimation

---

src/loc/record/AddTokensRecordDialog.tsx

logion-network/logion-internal#1060

Add tokens record fees estimation dialog.

---

src/ClientExtrinsicSubmitter.tsx
src/ExtrinsicSubmissionResult.tsx
src/ExtrinsicSubmitter.test.tsx
src/ExtrinsicSubmitter.tsx
src/loc/CloseLocButton.test.tsx
src/loc/ImportItems.test.tsx
src/loc/LocCreationDialog.test.tsx
src/loc/LocPublishButton.test.tsx
src/loc/RequestVoteButton.test.tsx
src/loc/VoidLocButton.test.tsx
src/loc/VoidLocButton.tsx
src/loc/VoidLocReplaceExistingButton.test.tsx
src/loc/issuer/IssuerSelectionCheckbox.test.tsx
src/logion-chain/LogionChainContext.tsx
src/logion-chain/__mocks__/LogionChainMock.ts
src/settings/ChainData.test.tsx
src/test/Util.ts
src/wallet-user/trust-protection/CreateProtectionRequestForm.test.tsx
src/wallet-user/trust-protection/ProtectionRecoveryRequest.test.tsx

* "Persistent" module-level state is moved to context.
logion-network/logion-internal#1061

Move extrinsic submission to context

---

src/common/ButtonGroup.css
src/loc/CollectionLocItemChecker.test.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/DashboardCertificate.tsx
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap
src/loc/__snapshots__/DashboardCertificate.test.tsx.snap

* Adds description column to items table
* Frees up space for the new column by moving SoF button to item view (advanced feature that does not need to be quickly accessible directly from the table)
logion-network/logion-internal#1070

Add description column to items table

---

src/common/Button.css
src/loc/AcceptRejectLocRequest.test.tsx
src/loc/AcceptRejectLocRequest.tsx
src/loc/__snapshots__/AcceptRejectLocRequest.test.tsx.snap

logion-network/logion-internal#1073

Prevent LOC accept with non-accepted items

---

src/ExtrinsicSubmissionStateView.tsx
src/common/CommonContext.tsx
src/common/WalletGauge.tsx
src/common/__snapshots__/WalletGauge.test.tsx.snap
src/loc/CloseLocButton.test.tsx
src/loc/CloseLocButton.tsx
src/logion-chain/__mocks__/LogionChainMock.ts
src/logion-chain/index.tsx

* Apply approach described in https://github.com/logion-network/logion-wallet/pull/531 to LOC closing and token transfer
* Implement transaction polling in `CommonContext` in order to eventually remove `TransactionConfirmation` component (see token transfer for an illustration)

Fix transfer and refactor close

---

src/loc/OpenLoc.tsx

* Fixes infinite loop on extrinsic submission error (e.g. cancel by user)

Fix open LOC

---

src/loc/CustomItemActions.test.tsx
src/loc/LocItem.tsx
src/loc/TemplateItemActions.test.tsx
src/loc/__snapshots__/CustomItemActions.test.tsx.snap
src/loc/__snapshots__/TemplateItemActions.test.tsx.snap

logion-network/logion-internal#1076

No removal when item accepted

---

src/loc/VoidLocButton.test.tsx
src/loc/VoidLocButton.tsx
src/loc/VoidLocReplaceExistingButton.test.tsx
src/loc/VoidLocReplaceExistingButton.tsx
yarn.lock

* Use client with cancelPreVoid;
* Use submitCall and extrinsicSubmissionState. (fix endless loop)
logion-network/logion-internal#1040
logion-network/logion-internal#1084

Fix LOC Voiding.

---

package.json
src/vault/VaultOutRequest.tsx
src/wallet-user/UserContext.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/transaction-protection/LocCreationForm.tsx
src/wallet-user/trust-protection/IdentityLocRequest.test.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx
src/wallet-user/trust-protection/ProtectionRecoveryRequest.tsx
src/wallet-user/trust-protection/SelectLegalOfficer.tsx
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
yarn.lock

* Workload of each LLO is fetched by User context.
* Workload is displayed next to LLO's name in selection dropdown.
* There is one HTTP request per workload fetched, there is room for optimization but this will be the object of another PR.
logion-network/logion-internal#1136

Display LLO workload in select

---

package.json
src/common/TestData.ts
src/vault/VaultOutRequest.tsx
src/wallet-user/UserContext.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/transaction-protection/LocCreationForm.tsx
src/wallet-user/trust-protection/SelectLegalOfficer.tsx
src/wallet-user/trust-protection/VaultRecoveryProcessTab.tsx
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/ProtectionRecoveryRequest.test.tsx.snap
yarn.lock

* Use LLO workload cached in client.
* This makes the workload map useless in user context.
Companion of https://github.com/logion-network/logion-api/pull/232
logion-network/logion-internal#1136

Use optimized legal offcier workload

---

src/wallet-user/IdentityLocCreation.tsx
src/wallet-user/UserRouter.tsx
src/wallet-user/__snapshots__/UserRouter.test.tsx.snap
src/wallet-user/transaction-protection/LocCreation.test.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/trust-protection/IdentityLocRequest.tsx
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap

Identity LOC request:
* Restore previous behaviour: use `IdentityLocCreation`.
* Prevent misuse of `LocCreation`.
logion-network/logion-internal#1176

fix: restore identity LOC creation.

---

package.json
src/loc/CertificateAndLimits.test.tsx
src/loc/CertificateAndLimits.tsx
src/loc/ImportItems.tsx
src/loc/OpenLoc.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
yarn.lock

* use to latest client (`collectionParams` added and `openCollection` removed);
* provide stubbed implementation of collection request. (TODO's intentionally left).
logion-network/logion-internal#1179

Collection Params - first step

---

src/certificate/Certificate.css
src/certificate/Certificate.tsx
src/certificate/CollectionItemCellRow.css
src/certificate/LegalOfficerRow.tsx
src/certificate/TokensRecords.css

* Covers story https://github.com/logion-network/logion-internal/issues/1235
* Fixes check tools
* No item nor tokens record check for files
* Restricted delivery checks were still using wrong hash equality
logion-network/logion-internal#1236

Keep LLO contact always below LOC info

---

package.json
src/loc/IdentityLocRequest.test.tsx
src/loc/IdentityLocRequest.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
yarn.lock

Companion of https://github.com/logion-network/logion-api/pull/257
logion-network/logion-internal#1239

Prevent creation of redundant IDLOC

---

src/common/AmountFormat.tsx
src/loc/fees/EstimatedFees.tsx
src/loc/fees/__snapshots__/EstimatedFees.test.tsx.snap

logion-network/logion-internal#1233

Shows undefined fees inclusion/total with a dash.

---

package.json
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.test.tsx
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.tsx
yarn.lock

logion-network/logion-internal#1257

Use actual call to submit a secret recovery request

---

package.json
src/PublicPaths.tsx
src/PublicRouter.tsx
src/common/FormGroup.tsx
src/common/__snapshots__/AccountInfo.test.tsx.snap
src/common/__snapshots__/ComparableField.test.tsx.snap
src/common/__snapshots__/Identity.test.tsx.snap
src/common/__snapshots__/PostalAddress.test.tsx.snap
src/loc/__snapshots__/CollectionLocItemChecker.test.tsx.snap
src/loc/record/__snapshots__/TokensRecordFrame.test.tsx.snap
src/pages/public/secretdownload/SecretDownloadForm.test.tsx
src/pages/public/secretdownload/SecretDownloadForm.tsx
src/pages/public/secretdownload/SecretDownloadPage.css
src/pages/public/secretdownload/SecretDownloadPage.test.tsx
src/pages/public/secretdownload/SecretDownloadPage.tsx
src/pages/public/secretdownload/__snapshots__/SecretDownloadForm.test.tsx.snap
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.test.tsx
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/265
* Download page link is shown on successful creation of a secret recovery request
* Download page shows read-only parameters and a download button.
logion-network/logion-internal#1276

Add secret download page

---

package.json
src/legal-officer/LegalOfficerContext.tsx
src/logion-chain/LogionChainContext.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/271
logion-network/logion-internal#1292

Use decentralized directory

---

public/assets/not_closed_certificate_background.svg
src/certificate/Certificate.css
src/certificate/Certificate.tsx

* A warning is now displayed on the certificate of non-closed LOCs which are not void.
* The UI is similar to void LOCs: a warning message on top and a watermarked warning.
logion-network/logion-internal#1295

Temporary certificate

---

package.json
src/legal-officer/TestData.tsx
src/legal-officer/recovery/RecoveryRequestStatus.tsx
src/logion-chain/LogionChainContext.tsx
src/settings/DirectoryData.tsx
src/wallet-user/protection/LegalOfficers.tsx
src/wallet-user/protection/ProtectionRecoveryRequest.tsx
src/wallet-user/protection/RecoveryRefusal.tsx
src/wallet-user/protection/SelectLegalOfficer.tsx
src/wallet-user/recovery/WalletRecoveryProcessTab.test.tsx
yarn.lock

Companion of https://github.com/logion-network/logion-api/pull/272
* Fixes some wrong imports.
logion-network/logion-internal#1292

Fix create or update llo

---

src/common/AddressSwitcher.tsx
src/common/CommonContext.tsx
src/common/__mocks__/CommonContextMock.ts

logion-network/logion-internal#1307

Show all balances in switcher

---

package.json
yarn.lock

Companion of https://github.com/logion-network/logion-backend-ts/pull/314
Companion of https://github.com/logion-network/logion-api/pull/275
logion-network/logion-internal#1312

Update client (add address type when fetching loc requests).
