logion-network/logion-wallet

src/common/Authentication.test.tsx
src/common/Authentication.tsx

logion-network/logion-internal#164

feat: adapt authentication api call to fetch expiration timestamp.

---

src/wallet-user/trust-protection/ProtectionRecoveryRequest.css
src/wallet-user/trust-protection/ProtectionRecoveryRequest.tsx
src/wallet-user/trust-protection/ProtectionRefusal.tsx
src/wallet-user/trust-protection/RecoveryRefusal.tsx
src/wallet-user/trust-protection/__snapshots__/ProtectionRecoveryRequest.test.tsx.snap

* Display the second LO in case of double refusal.
* Swap the button and drop box to select another LO.
* Center Activate and Claim buttons.
logion-network/logion-internal#500

feat: improve layout of protection/recovery request 

---

src/common/TransactionType.test.tsx
src/common/TransactionType.tsx
src/common/__snapshots__/TransactionType.test.tsx.snap

* Forces definition of transaction type for every logion pallet/method.
* Provides a meaningful fallback.

feat: improve transaction type.

---

src/__mocks__/@logion/client.ts
src/common/ViewFileButton.tsx
src/loc/FileModel.test.ts
src/loc/FileModel.ts
src/loc/LocPrivateFileButton.tsx
src/loc/LocPrivateFileForm.tsx
yarn.lock

* Uploaded file name is re-used as document name when adding a file to a LOC
* On file download/view, file name is conditionally fixed (i.e. only if original file name does not already end with a valid extension)
logion-network/logion-internal#613

Fix file names

---

src/legal-officer/LegalOfficerContext.tsx
src/legal-officer/__mocks__/LegalOfficerContextMock.tsx
src/legal-officer/transaction-protection/PendingLocRequests.tsx
src/loc/AcceptRejectLocRequest.test.tsx
src/loc/AcceptRejectLocRequest.tsx
src/loc/CloseLocButton.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/DashboardCertificate.tsx
src/loc/LegalOfficerLocContext.test.tsx
src/loc/LegalOfficerLocContext.tsx
src/loc/LocContext.test.tsx
src/loc/LocContext.tsx
src/loc/UserLocContext.test.tsx
src/loc/UserLocContext.tsx
src/loc/__snapshots__/LegalOfficerLocContext.test.tsx.snap
src/loc/__snapshots__/UserLocContext.test.tsx.snap
src/loc/archive/ArchiveButton.tsx
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsRequestButton.tsx
src/wallet-user/__mocks__/UserContextMock.tsx
src/wallet-user/transaction-protection/DraftLocs.tsx
src/wallet-user/transaction-protection/RejectedLocs.tsx
src/wallet-user/transaction-protection/RequestedLocs.tsx

* `LocContext` now receives a `LocRequestState` which enables to minimize the number of HTTP requests on state transitions (no more useless fetches as `LocsState` is updated by SDK without the need for an explicit resync with backend and chain)
* Resync is still forced when clicking on main-menu items

Improve LOC context performance

---

src/__mocks__/@logion/client.ts
src/__mocks__/LogionClientMock.ts
src/legal-officer/client.test.ts
src/legal-officer/client.ts
src/loc/ContextualizedLocDetails.tsx
src/loc/LegalOfficerLocContext.tsx
src/loc/LocContext.test.tsx
src/loc/LocContext.tsx
src/loc/LocCreationDialog.tsx
src/loc/LocDetailsTab.test.tsx
src/loc/LocDetailsTab.tsx
src/loc/LocItems.test.tsx
src/loc/LocItems.tsx
src/loc/LocLinkButton.tsx
src/loc/LocLinkExistingLocDialog.tsx
src/loc/LocPrivateFileButton.test.tsx
src/loc/LocPrivateFileButton.tsx
src/loc/LocPublicDataButton.test.tsx
src/loc/LocPublicDataButton.tsx
src/loc/Model.test.tsx
src/loc/Model.tsx
src/loc/UserContextualizedLocDetails.tsx
src/loc/__mocks__/LocContextMock.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/wallet-user/UserContext.tsx

* Removed `addMetadata`, `addFile`, `addLink` and `deleteFile` functions from context
* Replaced by `mutateLocState` and a call to the state's method in the mutator
* Other methods will be handled later

Simplify LOC context

---

src/ClientExtrinsicSubmitter.tsx
src/common/Model.tsx
src/common/__mocks__/Model.tsx
src/common/__mocks__/ModelMock.ts
src/legal-officer/client.test.ts
src/legal-officer/client.ts
src/loc/LocContext.test.tsx
src/loc/LocContext.tsx
src/loc/LocLinkButton.tsx
src/loc/LocLinkExistingLocDialog.tsx
src/loc/LocPublishButton.test.tsx
src/loc/LocPublishButton.tsx
src/loc/LocPublishLinkButton.tsx
src/loc/LocPublishPrivateFileButton.tsx
src/loc/LocPublishPublicDataButton.tsx
src/loc/__snapshots__/LocPublishLinkButton.test.tsx.snap
src/loc/__snapshots__/LocPublishPrivateFileButton.test.tsx.snap
src/loc/__snapshots__/LocPublishPublicDataButton.test.tsx.snap
src/loc/types.ts
src/logion-chain/__mocks__/LogionChainMock.ts
yarn.lock

* Publication logic was rewritten in a way more similar to logion SDK
* `mutateLocState` is used for publication
logion-network/logion-internal#643

Refactor item publish/confirm

---

src/__mocks__/LogionClientMock.ts
src/legal-officer/client.test.ts
src/legal-officer/client.ts
src/loc/LocContext.test.tsx
yarn.lock

* Each time a LOC state is involved, enforce use of current state.
* Collect all LOC data before awaiting (on await, execution thread may switch and cause the state to be discarded).
* After interactions with chain or backend, enforce refresh from current state.
logion-network/logion-internal#693

Fix state discarded issues with LOG operations

---

src/loc/statement/SofFilesAndDeliveriesEN.tsx
src/loc/statement/SofFilesAndDeliveriesFR.tsx
src/loc/statement/SofParams.ts
src/loc/statement/SofTokensRecordEN.tsx
src/loc/statement/SofTokensRecordFR.tsx
src/loc/statement/StatementOfFactsButton.tsx
src/loc/statement/StatementOfFactsTemplateEN.tsx
src/loc/statement/StatementOfFactsTemplateFR.tsx

* Tokens records are now present in both EN and FR Statement of Facts.
* The layout of a file with its deliveries being the same for collection item and token records and is thus factored to a new component: `SofFilesAndDeliveries[FR|EN].jsx]`.
logion-network/logion-internal#802

Add tokens records to SOF.

---

src/common/TestData.ts
src/loc/__snapshots__/LegalOfficerLocContext.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/settings/DirectoryData.tsx
src/wallet-user/trust-protection/__snapshots__/CreateProtectionRequestForm.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/IdentityLocRequest.test.tsx.snap
src/wallet-user/trust-protection/__snapshots__/ProtectionRecoveryRequest.test.tsx.snap
yarn.lock

* Removal of `logionUrl` is propagated to front-end. Note that it was anyway no more used.
logion-network/logion-internal#924

Remove logionUrl.

---

src/Login.css
src/Login.tsx
src/Main.tsx
src/__snapshots__/Login.test.tsx.snap
src/landing/LandingPage.tsx
src/landing/__snapshots__/LandingPage.test.tsx.snap
src/logion-chain/LogionChainContext.tsx

* A button was added on login screen to explicitly activate MetaMask (which is no more automatically enabled by default).
* It is now possible to go to login screen from landing page by activating MetaMask only.
* Login failures are now properly reported to user.
logion-network/logion-internal#972

Manual activation of MetaMask

---

package.json
src/Main.tsx
src/logion-chain/LogionChainContext.tsx
yarn.lock

* Call new async `isExtensionAvailable()`
* This avoids the problem of the Polkadot extension not being detected under Firefox.
* Unfortunately in Firefox the first call returns (very often) false, thus briefly showing the 3-steps extension installation screen.
logion-network/logion-internal#973

Call async isExtensionAvailable()

---

src/common/AmountControl.tsx
src/common/TransactionType.tsx
src/common/Wallet.tsx
src/components/collapsepane/CollapsePane.css
src/components/collapsepane/CollapsePane.tsx
src/components/identity/CollectionInfo.tsx
src/legal-officer/transaction-protection/LocRequestAcceptanceAndCreation.test.tsx
src/loc/AcceptRejectLocRequest.test.tsx
src/loc/LegalFeeAmount.tsx
src/loc/LocDetailsTab.tsx
src/loc/TransactionInfo.css
src/loc/TransactionInfo.tsx
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
src/logion-chain/LogionChainContext.tsx
src/wallet-user/transaction-protection/LocCreation.tsx
src/wallet-user/transaction-protection/LocCreationForm.tsx
yarn.lock

* Requester may set a custom legal fee for transaction and collection LOCs.
* The field is not visible by default (using a collapse pane).
* Legal fee is now displayed in collection info and (new) transaction info boxes (above items); when default fee is applied, it is displayed.
* The fields in LOC creation dialog have been re-ordered to better follow logical flow (first choose a LLO, then a description, then ...).
logion-network/logion-internal#984

Enable custom legal fees

---

src/legal-officer/transaction-protection/LocRequestAcceptanceAndCreation.test.tsx
src/loc/LocItem.tsx
src/loc/LocItemFactory.ts
src/loc/LocTemplateItems.tsx
yarn.lock

* Add the attribute `defaultTitle` to LocItems. Intended use is to display a meaningful title when `data` is not available yet - typically when handling items from a template.
* inject `node-api` and `client` matching latest node.
logion-network/logion-internal#997

Template items default title

---

src/__mocks__/LogionClientMock.ts
src/components/toggle/Checkbox.tsx
src/loc/CloseLocButton.css
src/loc/CloseLocButton.test.tsx
src/loc/CloseLocButton.tsx
src/loc/LocDetailsTab.tsx
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap
yarn.lock

* Adds a toggle next to close button.
* Toggle is disabled if auto-ack is not possible.
* Auto-ack is enabled when toggle is turned on.
logion-network/logion-internal#1022

Enable close with auto-ack

---

src/loc/OpenLoc.css
src/loc/OpenLoc.tsx
yarn.lock

* Depends on https://github.com/logion-network/logion-api/pull/202
logion-network/logion-internal#1035

Enable auto-publish

---

package.json
src/__mocks__/@logion/client-browser.ts
src/loc/FileModel.test.ts
src/loc/FileModel.ts
src/loc/ImportItems.tsx
src/loc/LocPrivateFileButton.tsx
src/loc/record/AddTokensRecordDialog.tsx
src/logion-chain/LogionChainContext.tsx
src/settings/ValuesFiles.tsx
yarn.lock

* Companion of https://github.com/logion-network/logion-api/pull/205
logion-network/logion-internal#1046

Use client-browser

---

src/ExtrinsicSubmissionStateView.tsx
src/loc/AcknowledgeButton.tsx
src/logion-chain/LogionChainContext.tsx
src/logion-chain/index.tsx

* The fix is taken as an opportunity to refactor code and stop using effects to handle extrinsic submission.
* `ExtrinsicSubmissionStateView` is introduced to simplify display of `LogionChainContext`'s `extrinsicSubmissionState`.
* Calls are submitted directly by components using context's `submitCall(call)`.
* Submission state is explicitly cleared by calling `clearSubmissionState()`.
logion-network/logion-internal#1078

Acknowledgment of items

---

src/ExtrinsicSubmissionStateView.tsx
src/common/WalletGauge.tsx
src/loc/CloseLocButton.tsx
src/loc/ImportItems.test.tsx
src/loc/ImportItems.tsx
src/loc/LocItem.tsx
src/loc/LocPublishButton.test.tsx
src/loc/LocPublishButton.tsx
src/loc/OpenLoc.tsx
src/loc/RequestVoteButton.test.tsx
src/logion-chain/LogionChainContext.tsx
src/logion-chain/__mocks__/LogionChainMock.ts

* Use submitCall for LOC closing, token transfer, item publication
* Use submitCallBatch for item import (batch is handled at context level)
logion-network/logion-internal#1081

Fix close, transfer, publish, import

---

package.json
src/PublicPaths.tsx
src/PublicRouter.tsx
src/certificate/Certificate.test.tsx
src/certificate/Certificate.tsx
src/certificate/IntroductionText.tsx
src/certificate/TokensRecords.tsx
src/loc/ImportItemDetails.tsx
src/loc/record/TokensRecordTable.css
src/loc/record/TokensRecordTable.tsx
yarn.lock

* Tokens record has now its dedicated certificate, accessible via [https://certificate.logion.network/public/certificate/`{locId}`/record/`{tokensRecordId}`](https://certificate.logion.network/public/certificate/{locId}/record/{tokensRecordId}).
* Fix: QR code is now correct for every kind of certificate.
Makes use of https://github.com/logion-network/logion-api/commit/ac9a7a8e115031cdcae50e386b72688b53a1e890
logion-network/logion-internal#1154

Add Tokens record certificate.

---

src/certificate/TokensRecords.tsx
src/loc/record/TokensRecordFiles.css
src/loc/record/TokensRecordFiles.tsx
src/loc/record/TokensRecordTable.css
src/loc/record/TokensRecordTable.tsx

The actual model of Tokens Records and linked files is better displayed by:
* visually separating record from its files.
* showing all files if requested. 
* providing a decent yet perfectible style sheet - files attributes are styled pretty much like on the certificate.
* adding 2 new buttons under certificate column: copy/paste url and view QR-code.
This PR also implements [these suggestions](https://github.com/logion-network/logion-internal/issues/1155#issuecomment-1985140231).
logion-network/logion-internal#1154
logion-network/logion-internal#1155
logion-network/logion-internal#1158

Improve Tokens Records table

---

src/__mocks__/LogionClientMock.ts
src/certificate/Certificate.test.tsx
src/loc/CollectionLocItemChecker.tsx
src/loc/record/TokensRecordFiles.tsx
src/loc/record/TokensRecordFrame.css
src/loc/record/TokensRecordFrame.test.tsx
src/loc/record/TokensRecordFrame.tsx
src/loc/record/TokensRecordTable.tsx
src/loc/record/__snapshots__/TokensRecordFrame.test.tsx.snap

* Add a new button to check if a Tokens record with id is present in the collection.
* If the input value is not a hash, it will be considered as a business key, and hashed before search.
* A maximum size of 1000 is set to prevent crashing the front in case of huge tokens records set - to be adapted when real backend paging is available.
* Some minor fixes.
logion-network/logion-internal#1158

Tokens records search.

---

src/common/AccountAddress.test.tsx
src/common/AccountAddress.tsx
src/common/CommonContext.tsx
src/common/CopyPasteButton.tsx
src/common/Dashboard.css
src/common/Dashboard.tsx
src/common/__snapshots__/AccountAddress.test.tsx.snap
src/common/__snapshots__/Dashboard.test.tsx.snap

* Follows https://github.com/logion-network/logion-wallet/pull/553
* Same behavior as Polkadot.js (hover on address icon shows "copy" cursor and click actually copies to clipboard).
* Added a very simple notification framework (one notification at a time).
logion-network/logion-internal#1188

Enable address copy from selector

---

src/ExtrinsicSubmissionResult.test.tsx
src/ExtrinsicSubmitter.test.tsx
src/__snapshots__/ExtrinsicSubmissionResult.test.tsx.snap
src/common/PendingVaultTransferRequests.tsx
src/common/RequestToCancel.tsx
src/common/WalletGauge.tsx
src/common/__snapshots__/WalletGauge.test.tsx.snap
src/legal-officer/vault/PendingVaultTransferRequests.tsx
src/legal-officer/vault/VaultTransferRequestsHistory.tsx
src/loc/AcknowledgeButton.tsx
src/loc/LocPublishButton.test.tsx
src/loc/LocPublishButton.tsx
src/loc/__snapshots__/LocItems.test.tsx.snap
src/logion-chain/LogionChainContext.tsx
src/logion-chain/__mocks__/LogionChainMock.ts
src/logion-chain/__mocks__/SignatureMock.tsx

* Wait for in-block instead of finalization.
* Prevents acknowledgment if no timestamp (i.e. not yet synced backend-side).
* Close is already safe (cannot close if acknowledgement not yet synced, check in the SDK).
* Fixes bug about estimating fees when not relevant (threw an error in LLO UI, potentially with no impact in production but visible with development mode).
* Do not wait for transaction after successful LGNT transfer (but show a message telling there is a delay before it shows up in history). The logic in the context can be removed later.
logion-network/logion-internal#1222

Do not wait for finalization

---

package.json
yarn.lock

logion-network/logion-internal#1225

chore: update client (collection items order).

---

src/common/RequestToCancel.tsx
src/legal-officer/recovery/RecoveryDetails.tsx
src/legal-officer/vault/PendingVaultTransferRequests.tsx
src/loc/ContextualizedLocDetails.tsx
src/loc/LocPublishButton.tsx
src/loc/OpenLoc.tsx
src/loc/RestricedDeliveryCell.tsx
src/loc/UserContextualizedLocDetails.tsx
src/loc/VoidFrame.test.tsx
src/loc/VoidFrame.tsx
src/loc/VoidLocButton.test.tsx
src/loc/VoidLocButton.tsx
src/loc/VoidLocReplaceExistingButton.test.tsx
src/loc/VoidLocReplaceExistingButton.tsx
src/loc/__snapshots__/ContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/UserContextualizedLocDetails.test.tsx.snap
src/loc/__snapshots__/VoidFrame.test.tsx.snap
src/settings/ValuesFiles.tsx
src/vault/VaultOutRequest.tsx
src/wallet-user/protection/CreateProtectionRequestForm.tsx
src/wallet-user/protection/ProtectionRecoveryRequest.tsx

* Do not destroy component (open and void buttons) so that user can click on button triggering the submission state clearing.
* Systematically catch all errors thrown by `await submitCall(call)`.
logion-network/logion-internal#1134
logion-network/logion-internal#1194

Properly clear submission state after open and void

---

package.json
src/legal-officer/votes/Mocks.ts
src/legal-officer/votes/YourVote.tsx
src/loc/AcknowledgeButton.tsx
src/loc/CloseLocButton.tsx
src/loc/LocCreationDialog.test.tsx
src/loc/LocCreationSteps.tsx
src/loc/LocPublishLinkButton.tsx
src/loc/LocPublishPrivateFileButton.tsx
src/loc/LocPublishPublicDataButton.tsx
src/loc/OpenLoc.tsx
src/loc/VoidLocButton.tsx
src/loc/VoidLocReplaceExistingButton.tsx
src/loc/issuer/IssuerSelectionCheckbox.tsx
yarn.lock

Companion of https://github.com/logion-network/logion-api/pull/260
logion-network/logion-internal#1246

Update logion-client (BlockchainSubmission used everywhere).

---

package.json
src/Login.css
src/Login.tsx
src/PublicPaths.tsx
src/PublicRouter.tsx
src/__snapshots__/Login.test.tsx.snap
src/components/identity/IdentityForm.tsx
src/landing/LandingPage.css
src/landing/LandingPage.tsx
src/landing/__snapshots__/LandingPage.test.tsx.snap
src/loc/__snapshots__/IdentityLocRequest.test.tsx.snap
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestForm.tsx
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.css
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.test.tsx
src/pages/public/secretrecoveryrequest/SecretRecoveryRequestFormPage.tsx
yarn.lock

* Secret recovery request page is public i.e. does not require authentication.
* The page is reachable from landing page (no extension enabled) or login page (with any extension enabled).
* Actual data submission to backend is not yet implemented.
logion-network/logion-internal#1257

Add secret recovery request form

---

package.json
src/loc/record/AddTokensRecordDialog.tsx
yarn.lock

* Adds checkbox to "Add tokens record" dialog
* Beware the hack to make things compile despite the react-hook-form controlled react-bootstrap control
* Fix form validation (errors where not shown)
logion-network/logion-internal#1281

Add "charge submitter" checkbox

---

public/config.js
src/PublicPaths.tsx
src/config/index.tsx

* App base URL can be provided by configuration.
logion-network/logion-internal#1306

Use persistent base URL

---

package.json
yarn.lock

logion-network/logion-internal#1298

Update client (human-readable message signature message).

---

src/loc/DataLocRequest.test.tsx
src/loc/DataLocRequest.tsx
src/loc/DraftLocInstructions.tsx
src/loc/LocDetailsTab.test.tsx
src/loc/LocDetailsTab.tsx
src/loc/LocLinkButton.test.tsx
src/loc/LocLinkExistingLocDialog.tsx
src/loc/__snapshots__/DraftLocInstructions.test.tsx.snap
src/loc/__snapshots__/LocDetailsTab.test.tsx.snap

* The user can now create draft data LOCs attached to a draft Identity LOC (i.e. the Identity LOC does not have to be closed anymore).
* Links can target draft LOCs (i.e. they do not have to be on-chain anymore).
* Draft request submission is only possible when Identity LOC is closed and all links target closed LOCs.
* Draft request cancellation is only possible if no incoming links exist and, if an Identity LOC, no other LOCs are attached to it.
logion-network/logion-internal#1318

Enable full-draft mode
